Streaming files as partial content
vapor/vapor pull request #2342
Opened 2020-05-01 17:37 UTC by AKazm

Vapor's `FileIO.streamFile` will take `Range` headers into regard and return `206 Partial Content` with `Content Range` headers. This is useful for streaming content such as video files. These headers, along with correct response bodys, are required [by browsers like Safari](https://developer.apple.com/library/archive/documentation/AppleApplications/Reference/SafariWebContent/CreatingVideoforSafarioniPhone/CreatingVideoforSafarioniPhone.html#//apple_ref/doc/uid/TP40006514-SW6).

2020-05-02 12:59 UTC, AKazm commented
I've noticed two bugs in there:

- `asByteBufferBounds()` returnend incorrect values (fixed)
- Incorrect parsing of range headers; fixed that, too.

2020-05-02 15:55 UTC, grosch commented on Sources/Vapor/HTTP/Headers/HTTPHeaders+ContentRange.swift
> +    public func asHeaderString() -> String {
Can this be renamed `serialize()` to be consistent with many areas of Vapor?

2020-05-02 15:58 UTC, grosch commented on Sources/Vapor/HTTP/Headers/HTTPHeaders+ContentRange.swift
> +        if ranges.filter({ $0 == nil }).count > 0 {
Please use `!ranges.filter({ $0 == nil}).isEmpty` as it's more efficient.

2020-05-02 15:58 UTC, AKazm commented
Although it would somewhat obfuscate the method's purpose, it's fine by me, since consistency is important, too.

2020-05-02 15:59 UTC, grosch commented on Sources/Vapor/HTTP/Headers/HTTPHeaders+ContentRange.swift
> +    func asHeaderString() -> String {
Please use `serialize()`

2020-05-02 16:00 UTC, grosch commented on Sources/Vapor/HTTP/Headers/HTTPHeaders+ContentRange.swift
> +        guard let contentRange = ResponseContentRange.from(responseStr: rangeStr) else {
Please move this to the line right after you assign `rangeStr`

2020-05-02 16:00 UTC, grosch commented on Sources/Vapor/HTTP/Headers/HTTPHeaders+ContentRange.swift
> +    func asHeaderString() -> String {
Rename to `serialize()`

2020-05-02 16:01 UTC, grosch commented on Sources/Vapor/HTTP/Headers/HTTPHeaders+ContentRange.swift
> +        if ranges.count > 2 {
Swap to a `guard` please.

2020-05-02 16:01 UTC, grosch commented on Sources/Vapor/HTTP/Headers/HTTPHeaders+ContentRange.swift
> +    public func asHeaderString() -> String {
`serialize()` please

2020-05-02 16:02 UTC, grosch commented on Sources/Vapor/HTTP/Headers/HTTPHeaders+ContentRange.swift
> +    public func asHeaderString() -> String {
`serialize()` please :)

2020-05-02 16:04 UTC, grosch commented
Please add unit tests as well.

2020-05-02 16:49 UTC, AKazm commented
- renamed `asHeaderString()` to `serialize()`
- added tests for serialization of ranges and content ranges
- added tests for deserialization of ranges and content ranges
- resolved all code style issues mentioned by @grosch (except for "Please move this to the line right after you assign `rangeStr`", since I seriously don't get it :()

2020-05-02 16:53 UTC, AKazm commented on Sources/Vapor/HTTP/Headers/HTTPHeaders+ContentRange.swift
> +    func asHeaderString() -> String {
Done.

2020-05-02 16:53 UTC, AKazm commented on Sources/Vapor/HTTP/Headers/HTTPHeaders+ContentRange.swift
> +    func asHeaderString() -> String {
Done.

2020-05-02 16:53 UTC, AKazm commented on Sources/Vapor/HTTP/Headers/HTTPHeaders+ContentRange.swift
> +        if ranges.count > 2 {
Done.

2020-05-02 16:53 UTC, AKazm commented on Sources/Vapor/HTTP/Headers/HTTPHeaders+ContentRange.swift
> +    public func asHeaderString() -> String {
Done.

2020-05-02 16:56 UTC, AKazm commented on Sources/Vapor/HTTP/Headers/HTTPHeaders+ContentRange.swift
> +        guard let contentRange = ResponseContentRange.from(responseStr: rangeStr) else {
I'm absolutely don't know what you mean by that. Which line should be moved?

2020-05-02 16:57 UTC, AKazm commented on Sources/Vapor/HTTP/Headers/HTTPHeaders+ContentRange.swift
> +    public func asHeaderString() -> String {
Done.

2020-05-02 16:57 UTC, AKazm commented on Sources/Vapor/HTTP/Headers/HTTPHeaders+ContentRange.swift
> +        if ranges.filter({ $0 == nil }).count > 0 {
Done.

2020-05-02 16:57 UTC, AKazm commented on Sources/Vapor/HTTP/Headers/HTTPHeaders+ContentRange.swift
> +    public func asHeaderString() -> String {
Done.

2020-05-02 16:59 UTC, grosch commented on Sources/Vapor/HTTP/Headers/HTTPHeaders+ContentRange.swift
> +        guard let contentRange = ResponseContentRange.from(responseStr: rangeStr) else {
You assign `rangeStr` on line 64.  So move the entire guard block to right after line 64.  No need to set `self.unit` if you're going to leave the method.

2020-05-02 17:03 UTC, grosch commented on Tests/VaporTests/HTTPHeaderTests.swift
> +    func testContentRangeSerialization() throws {
This is more just a style thing, so feel free to ignore, but this is really three separate tests, and so should be three separate test methods.  Same with `testContentRangeDeserialization`

2020-05-02 17:12 UTC, AKazm commented on Sources/Vapor/HTTP/Headers/HTTPHeaders+ContentRange.swift
> +        guard let contentRange = ResponseContentRange.from(responseStr: rangeStr) else {
Done.

2020-05-02 17:15 UTC, AKazm commented on Tests/VaporTests/HTTPHeaderTests.swift
> +    func testContentRangeSerialization() throws {
Never did something like this before, to be honest.

So I did read some of the tests before and since there are several cases of tests containing multiple `XCTAsserEqual`, I thought this would be fine, since each tests covers the same functionality in one isolated "area".

2020-05-02 17:16 UTC, AKazm commented on Sources/Vapor/HTTP/Headers/HTTPHeaders+ContentRange.swift
> +        guard let contentRange = ResponseContentRange.from(responseStr: rangeStr) else {
Done.

2020-05-03 11:31 UTC, MrLotU commented on Sources/Vapor/HTTP/Headers/HTTPHeaders+ContentRange.swift
> +            .map { it in RequestedRange.from(requestStr: it) }
```suggestion
            .map(RequestedRange.from)
```

2020-05-03 11:36 UTC, MrLotU commented on Sources/Vapor/HTTP/Headers/HTTPHeaders+ContentRange.swift
> +            .map({ $0.trimmingCharacters(in: .whitespacesAndNewlines) })
Don't need the `()` around the closure here. 
```suggestion
            .map { $0.trimmingCharacters(in: .whitespacesAndNewlines) }
```

2020-05-03 11:38 UTC, MrLotU commented on Sources/Vapor/HTTP/Headers/HTTPHeaders+ContentRange.swift
> +        guard let start = Int(ranges[0]) else {
I think we need a check on `ranges.count > 0` or `!ranges.isEmpty` otherwise this _could_ crash with an `Index out of bound`

2020-05-03 11:39 UTC, MrLotU commented on Sources/Vapor/HTTP/Headers/HTTPHeaders+ContentRange.swift
> +        let start = Int(ranges[0])
Same `ranges.count > 0` or `!ranges.isEmpty` required here 😃

2020-05-03 11:41 UTC, MrLotU commented on Sources/Vapor/HTTP/Headers/HTTPHeaders+ContentRange.swift
> +                let int64Value = NSNumber(value: value).int64Value
Specific reason for `NSNumber` here? Why not `Int64(value)`?

2020-05-03 11:49 UTC, AKazm commented on Sources/Vapor/HTTP/Headers/HTTPHeaders+ContentRange.swift
> +        guard let start = Int(ranges[0]) else {
`ranges.count` cannot be `0` because i'm not omitting empty subsequences (i think?!)

2020-05-03 11:50 UTC, AKazm commented on Sources/Vapor/HTTP/Headers/HTTPHeaders+ContentRange.swift
> +        let start = Int(ranges[0])
same: `ranges.count` cannot be `0` because i'm not omitting empty subsequences (i think?!)

2020-05-03 11:55 UTC, MrLotU commented on Sources/Vapor/HTTP/Headers/HTTPHeaders+ContentRange.swift
> +        guard let start = Int(ranges[0]) else {
Ah. My bad. You're correct
```
  1> "".split(separator: "/") 
$R0: [String.SubSequence] = 0 values
  2> "".split(separator: "/", omittingEmptySubsequences: false).map(String.init) 
$R1: [String] = 1 value {
  [0] = ""
}
```

2020-05-03 11:56 UTC, AKazm commented on Sources/Vapor/HTTP/Headers/HTTPHeaders+ContentRange.swift
> +                let int64Value = NSNumber(value: value).int64Value
well, i've used mutliple programming languages in my lifetime, none of them offered a safe way to convert `Int` to `Int64` or the other way around using a constructor (throwing, crashing, ..)

so, this is just based on an educated guess (which often turns out to be wrong when it comes to Swift, since Swift is very exotic compared to most languages). If I'm wrong here, I'm happy to learn something new!

2020-05-03 12:23 UTC, AKazm commented on Sources/Vapor/Utilities/FileIO.swift
> +            (offset, byteCount) = contentRange.ranges[0].asByteBufferBounds(withMaxSize: fileSize)
I notice undefined behaviour here if the requested range exceeds the file size. Any proposals here?

2020-05-06 07:41 UTC, Joannis commented on Sources/Vapor/HTTP/Headers/HTTPHeaders+ContentRange.swift
> +                let int64Value = NSNumber(value: value).int64Value
Int and Int64 are practically the exact same type (although the compiler won't recognize it as such) unless you're running on a 32-bit platform. But who does that, and why would you want to support 32 bit platforms?

So because Int equals Int64 you're safe to do so.

2020-05-06 07:44 UTC, Joannis commented on Sources/Vapor/Utilities/FileIO.swift
> +            let range = contentRange.ranges[0].asResponseContentRange(limit: fileSize)
Is it safe to assume `!contentRange.ranges.isEmpty`? If it would be `[]` then this code will cause a crash for sure.

2020-05-06 07:45 UTC, AKazm commented on Sources/Vapor/HTTP/Headers/HTTPHeaders+ContentRange.swift
> +                let int64Value = NSNumber(value: value).int64Value
I know about the quality of those types, what was especially confusing to me was SwiftNIOs explicit offset for reading files, which is of type `Int64`. If Vapor does not support 32bit systems, then I'll change it to initializer invocations alter today!

2020-05-06 07:48 UTC, AKazm commented on Sources/Vapor/Utilities/FileIO.swift
> +            let range = contentRange.ranges[0].asResponseContentRange(limit: fileSize)
It is, since `contentRange` is `nil` if `ranges.count` is `!= 1` (see lines 122-124)

2020-05-06 07:48 UTC, Joannis commented
Thanks so much for this PR. I'm afraid I don't have a quick solution for your question. But a `.badRequest` error would be an option in my book.

2020-05-06 07:49 UTC, Joannis commented on Sources/Vapor/Utilities/FileIO.swift
> +            let range = contentRange.ranges[0].asResponseContentRange(limit: fileSize)
Thanks, I definitely overlooked that

2020-05-06 07:49 UTC, AKazm commented
One option would be to return 416, another would be to just return the whole file instead. Both options would be valid, I'd prefer a configurable solution with a reasonable default.

2020-05-06 07:53 UTC, Joannis commented on Sources/Vapor/HTTP/Headers/HTTPHeaders+ContentRange.swift
> +                let int64Value = NSNumber(value: value).int64Value
I can imagine! NIO is a pretty broad and a _very_ correct implementation.

2020-05-08 19:27 UTC, tanner0101 commented on Sources/Vapor/HTTP/Headers/HTTPHeaders+ContentRange.swift
> +public struct RangeHeader : Equatable {
These types should ideally be nested inside of `HTTPHeaders`. See https://github.com/vapor/vapor/blob/master/Sources/Vapor/HTTP/Headers/HTTPHeaders%2BContentDisposition.swift#L20 for a good example to copy.

2020-05-08 19:31 UTC, tanner0101 commented on Sources/Vapor/HTTP/Headers/HTTPHeaders+ContentRange.swift
> +            return contains(name: .contentRange)
This should be using the `parseDirectives` methods. This takes care of a lot of weird edge cases in HTTP header values automatically. 

Again HTTPHeaders+ContentDisposition is a good example to follow here: https://github.com/vapor/vapor/blob/master/Sources/Vapor/HTTP/Headers/HTTPHeaders%2BContentDisposition.swift#L20

2020-05-08 19:34 UTC, tanner0101 commented on Sources/Vapor/HTTP/Headers/HTTPHeaders+ContentRange.swift
> +    public let range: ResponseContentRange
Instead of an enum, what about something like:
```swift
public var range: Range<Int>?
public var size: Int?
```
Where `nil` on either is serialized as `*`.

2020-05-08 19:37 UTC, tanner0101 commented on Sources/Vapor/HTTP/Headers/HTTPHeaders+ContentRange.swift
> +    public let ranges: [RequestedRange]
Could we use `Swift.Range` here instead?

2020-05-08 19:37 UTC, tanner0101 commented on Sources/Vapor/HTTP/Headers/HTTPHeaders+ContentRange.swift
> +public enum RequestedRange : Equatable {
This could be nested in `HTTPHeaders.Range`

2020-05-08 19:40 UTC, tanner0101 commented on Sources/Vapor/Utilities/FileIO.swift
> +                         onRead: onRead)
No "xcode" indentation please. Look at other files to see how long method names are indented.

2020-05-08 19:42 UTC, tanner0101 commented on Sources/Vapor/Utilities/FileIO.swift
> +        if let contentRange = contentRange {
I think it would be more readable to have the above variables as `let` and set the default values in an `else`.

2020-05-08 19:47 UTC, tanner0101 commented on Sources/Vapor/HTTP/Headers/HTTPHeaders+ContentRange.swift
> +    public func asByteBufferBounds(withMaxSize size: Int) -> (offset: Int64, byteCount: Int) {
We should be fine to just use `numericCast` here when we need to convert Int -> Int64. I'd much rather do that than use `NSNumber` without looking more deeply into the implementation. Who knows what dark magic Foundation is doing. 

Either way, this extension would make more sense next to the FileIO code as a private method.

2020-05-08 19:47 UTC, tanner0101 commented on Tests/VaporTests/HTTPHeaderTests.swift
> +                       ContentRangeHeader(unit: .bytes, range: .any(size: 1000)))
"xcode" formatting here, too

2020-05-08 20:15 UTC, AKazm commented on Sources/Vapor/HTTP/Headers/HTTPHeaders+ContentRange.swift
> +    public let range: ResponseContentRange
This actually has been my first approach on doing this, but I wanted to eliminate optionals here. Has the advantage of avoiding a lot of code cluttering.

If you insist on this change (same goes for Request Range), please confirm this!

2020-05-08 20:42 UTC, AKazm commented on Sources/Vapor/HTTP/Headers/HTTPHeaders+ContentRange.swift
> +public enum RequestedRange : Equatable {
This actually has been my first approach on doing this, but I wanted to eliminate optionals here. Has the advantage of avoiding a lot of code cluttering.

If you insist on this change (same goes for Response Content Range), please confirm this!

2020-05-08 20:43 UTC, AKazm commented on Sources/Vapor/HTTP/Headers/HTTPHeaders+ContentRange.swift
> +    public let ranges: [RequestedRange]
This actually has been my first approach on doing this, but I wanted to eliminate optionals here. Has the advantage of avoiding a lot of code cluttering.

If you insist on this change (same goes for Response Content Range), please confirm this!

2020-05-09 09:01 UTC, AKazm commented on Sources/Vapor/HTTP/Headers/HTTPHeaders+ContentRange.swift
> +            return contains(name: .contentRange)
Done, although I can't say I'd like it.

2020-05-26 21:15 UTC, tanner0101 submitted a review, later dismissed
The latest changes look good, thanks! Most of my comments here are style nits. Please take a look at the other source files in this project for comparison and follow their style. 

More importantly though, header value parsing should be handled by the `HTTPHeaders.Directive` helpers. From what I can tell this should handle the Range and ContentRange header syntax. Simple string parsing is error prone and will not handle edge cases.

2020-05-26 21:15 UTC, tanner0101 commented on Sources/Vapor/HTTP/Headers/HTTPHeaders+ContentRange.swift
> +public extension HTTPHeaders {
`public` keyword should go in front of each type definition / method.

2020-05-26 21:15 UTC, tanner0101 commented on Sources/Vapor/HTTP/Headers/HTTPHeaders+ContentRange.swift
> +
No new line here.

2020-05-26 21:15 UTC, tanner0101 commented on Sources/Vapor/HTTP/Headers/HTTPHeaders+ContentRange.swift
> +    enum RangeUnit : Equatable {
No space before colon.

2020-05-26 21:15 UTC, tanner0101 commented on Sources/Vapor/HTTP/Headers/HTTPHeaders+ContentRange.swift
> +                case .bytes:
Indentation.

2020-05-26 21:15 UTC, tanner0101 commented on Sources/Vapor/HTTP/Headers/HTTPHeaders+ContentRange.swift
> +        public init?(httpHeaders headers: HTTPHeaders) {
`HTTPHeaders` helpers should follow a similar pattern. `HTTPHeaders.ContentDisposition` is a good example. There should be internal `init?(directives: [Directive])` and `directives() -> [Directive]` methods that are used by a public mutable property like `public var contentDisposition: ContentDisposition?`.

2020-05-26 21:15 UTC, tanner0101 commented on Sources/Vapor/HTTP/Headers/HTTPHeaders+ContentRange.swift
> +            let splitResult = header.split(separator: "=", omittingEmptySubsequences: false)
This type of parsing should be handled by `parseDirectives` as it's non-trivial to get right. For example, your code here isn't taking into consideration quoted strings.

2020-05-26 21:15 UTC, tanner0101 commented on Sources/Vapor/Utilities/FileIO.swift
> +                           mediaType: HTTPMediaType? = nil) -> Response {
No editor assisted indentation, please. In other words, never indent more than one tab-width.

2020-05-26 21:15 UTC, tanner0101 commented on Sources/Vapor/Utilities/FileIO.swift
> +            onRead: onRead)
`)` on newline.

2020-05-26 21:15 UTC, tanner0101 commented on Sources/Vapor/Utilities/FileIO.swift
> +                return (offset: numericCast(size-value), byteCount: value)
Spaces around operators.

2020-05-28 06:26 UTC, AKazm commented
Will take a look at it on Saturday.

2020-05-31 22:51 UTC, AKazm commented
Done, @tanner0101!

2020-06-24 23:46 UTC, tanner0101 commented
@AKazm sorry for the late response. The latest updates look great, thank you! Would you mind adding some comments to the code? Public method docblocks and inline comments around terse code would be especially helpful. The header parsing tests are great. We should have at least one test ensuring the actual partial file reading works though. Ideally this would go through a real route. This file has some good examples: https://github.com/vapor/vapor/blob/master/Tests/VaporTests/FileTests.swift. Let me know if you need help writing that.

2020-06-25 05:52 UTC, AKazm commented
Comments won't be a problem, writing test code for streaming files is a thing I've never done before and since I'm kind of occupied for the next couple of weeks, any help on this would be appreciated.

2020-07-14 22:00 UTC, tanner0101 commented
@AKazm let me know when this is ready for another review. Thanks!

2020-07-15 06:34 UTC, AKazm commented
@tanner0101 Will take care of the tests on the weekend!

2020-07-19 18:39 UTC, AKazm commented
I'm sorry, but I simply couldn't do it this weekend, @tanner0101.

I didn't forget about it and I'll take care of it as soon as I can, probably on Tuesday afternoon, CEST.

2020-08-26 12:23 UTC, nerdsupremacist commented
@AKazm What's the status on this? I kinda need it right now.

I'll do a fork of this for now, please reach out if you need any help

2020-08-26 12:27 UTC, AKazm commented
It's a motivation for me that other people want this as well.

I promise to solve this during the wekeend. Time is a serious issue for me right now and I'm sorry for not having been able to continue here within the past few months.

**Any help is appreciated**.

2020-12-22 10:13 UTC, 0xTim requested changes
Thanks for doing this (and poking me!)

I think this is mostly good to go, just a few small things to clarify. Also, if you could update the PR comments as they'll become the release notes

2020-12-22 10:13 UTC, 0xTim commented on Sources/Vapor/HTTP/Headers/HTTPHeaders+ContentRange.swift
> +            guard let start = Int(ranges[0]) else {
Are there any scenarios where `range.count` can be 0? If so we should add a check here

2020-12-22 10:13 UTC, 0xTim commented on Sources/Vapor/HTTP/Headers/HTTPHeaders+ContentRange.swift
> +            let limits = ranges[1].split(separator: "/", omittingEmptySubsequences: false)
Again, we're not checking the array size before accessing here. If the array can be of size one or two, the guard at the top should be changed to reflect that

2020-12-22 10:13 UTC, 0xTim commented on Sources/Vapor/Utilities/FileIO.swift
> +            (offset, byteCount) = contentRange.ranges[0].asByteBufferBounds(withMaxSize: fileSize)
I think a bad request would be appropriate in this case

2020-12-22 10:13 UTC, 0xTim commented on Sources/Vapor/Utilities/FileIO.swift
> +            let range = contentRange.ranges[0].asResponseContentRange(limit: fileSize)
Again, not checking array size here before accessing

2020-12-22 11:46 UTC, siemensikkema reviewed
I left some suggestions to remove some force unwraps and to clarify the code here and there a bit.

2020-12-22 11:46 UTC, siemensikkema commented on Sources/Vapor/HTTP/Headers/HTTPHeaders+ContentRange.swift
> +    }
- Add a couple of `self`s to be in compliance with [the style guide](https://github.com/vapor/vapor/blob/master/.github/contributing.md)
- write getter in same style as for `range`
- use guard to avoid force unwrap
```suggestion
    public var contentRange: ContentRange? {
        get {
            return HTTPHeaders.ContentRange(directives: self.parseDirectives(name: .contentRange).flatMap { $0 })
        }
        set {
            if self.contains(name: .contentRange) {
                self.remove(name: .contentRange)
            }
            guard let newValue == newValue else {
                return
            }
            self.add(name: .contentRange, value: newValue.serialize())
        }
    }
```

2020-12-22 11:46 UTC, siemensikkema commented on Sources/Vapor/HTTP/Headers/HTTPHeaders+ContentRange.swift
> +        }
- Add a couple of selfs to be in compliance with the style guide
- use guard to avoid force unwrap
```suggestion
        get {
            return HTTPHeaders.Range(directives: self.parseDirectives(name: .range).flatMap { $0 })
        }
        set {
            if self.contains(name: .range) {
                self.remove(name: .range)
            }
            guard let newValue == newValue else {
                return
            }
            self.add(name: .range, value: newValue.serialize())
        }
```

2020-12-22 11:46 UTC, siemensikkema commented on Sources/Vapor/HTTP/Headers/HTTPHeaders+ContentRange.swift
> +            return .within(start: start!, end: end!)
This is a way to avoid force unwraps:
```suggestion
            let count = ranges.count
            guard count <= 2 else { return nil }
    
            switch (count > 0 ? Int(ranges[0]) : nil, count > 1 ? Int(ranges[1]) : nil) {
            case (nil, nil):
                return nil
            case let (.some(start), nil):
                return .start(value: start)
            case let (nil, .some(tail)):
                return .tail(value: tail)
            case let (.some(start), .some(end)):
                return .within(start: start, end: end)
            }
```

2020-12-22 11:46 UTC, siemensikkema commented on Sources/Vapor/HTTP/Headers/HTTPHeaders+ContentRange.swift
> +
```suggestion
```

2020-12-22 11:46 UTC, siemensikkema commented on Sources/Vapor/HTTP/Headers/HTTPHeaders+ContentRange.swift
> +            let limits = ranges[1].split(separator: "/", omittingEmptySubsequences: false)
One way to achieve that and maybe gain some code clarity is to switch over `ranges.count`. This also avoids recounting.

```swift
switch ranges.count {
case 1: ...
case 2: ...
default: // either 0 or >2 
    return nil
```

2020-12-22 11:46 UTC, siemensikkema commented on Sources/Vapor/Utilities/FileIO.swift
> +            : nil
```suggestion
        let contentRange = request.headers.range.map { range in
            guard range.unit == .bytes, range.ranges.count == 1 else {
                return nil
            }
            return range
        }
```

2020-12-22 11:46 UTC, siemensikkema commented on Sources/Vapor/Utilities/FileIO.swift
> +
```suggestion
```

2021-01-06 16:09 UTC, 0xTim commented
I think this is finally ready - @siemensikkema @gwynne if you want to do a final review.

@AKazm is there anything else that needs addressing before we merge?

2021-01-06 16:11 UTC, 0xTim approved these changes

2021-01-06 18:46 UTC, kylebrowning approved these changes

2021-01-06 18:46 UTC, kylebrowning commented on Sources/Vapor/Utilities/FileIO.swift
> +            fileSize.intValue,
nit: extra newline?

2021-01-07 07:50 UTC, AKazm commented on Sources/Vapor/Utilities/FileIO.swift
> +            fileSize.intValue,
> I think this is finally ready - @siemensikkema @gwynne if you want to do a final review.
> 
> @AKazm is there anything else that needs addressing before we merge?

Hello 0xTim,
please don't ask me for this. I've been in trouble since last year, I'm unfortunately occupied since my last activity here (since Corona gave our company many oppurtinities).

Nevertheless: I'm happy to see that there's some progress here made by other people since this is my first contribution to Open Source ever!

2021-01-07 07:57 UTC, siemensikkema approved these changes

2021-01-07 12:41 UTC, 0xTim commented
Confirmed I can play an MP4 in Safari so will merge, thank you everyone!

2021-01-07 12:42 UTC, merged

2021-01-07 12:42 UTC, tanner0101 commented
These changes are now available in [4.37.0](https://github.com/vapor/vapor/releases/tag/4.37.0)