Honor Configuration for Date Decoding & Encoding #2518
vapor/vapor pull request #2520
Opened 2020-10-30 09:50 UTC by andtie

Honor the configuration for Date Decoding & Encoding in `URLEncodedFormDecoder` / `URLEncodedFormEncoder` (fixes #2518).

```swift
// Configure a non-default date decoding strategy
let decoder = URLEncodedFormDecoder(configuration: .init(dateDecodingStrategy: .iso8601))
ContentConfiguration.global.use(urlDecoder: decoder)

// allow to use optional date-parameters in a request 
let after = try req.query.get(Date?.self, at: "after") ?? .distantPast
```

2020-10-30 14:25 UTC, siemensikkema reviewed
Thanks for this PR! I wonder if the title and description correctly reflect the changes, though. The configuration was used before, it was just not applied to optional dates, correct?

2020-10-30 14:25 UTC, siemensikkema commented on Sources/Vapor/URLEncodedForm/URLEncodedFormDecoder.swift
> +            //Check if we received a date. We need the decode with the appropriate format
```suggestion
            // Check if we received a date. We need the decode with the appropriate format.
```

2020-10-30 15:01 UTC, andtie commented
Thanks for your reply!

> I wonder if the title and description correctly reflect the changes, though. The configuration was used before, it was just not applied to optional dates, correct?

Yes, you are correct. How about "Honor Configuration for Decoding & Encoding of optional Dates"? 
I am very open for suggestions.

2020-11-02 12:34 UTC, 0xTim requested changes
One small nit on test name

2020-11-02 12:34 UTC, 0xTim commented on Tests/VaporTests/URLEncodedFormTests.swift
> +    func testGH2518() throws {
Small nit, can we rename this so it's clearer what the test achieves
```suggestion
    func testOptionalDateEncodingAndDecoding_GH2518() throws {
```

2020-11-02 14:20 UTC, 0xTim approved these changes
LGTM

2020-11-02 14:20 UTC, merged

2020-11-02 14:20 UTC, tanner0101 commented
These changes are now available in [4.34.1](https://github.com/vapor/vapor/releases/tag/4.34.1)