support automatic port picking
vapor/vapor pull request #2572
Opened 2021-02-24 18:36 UTC by weissi

- Allow automatic port picking by configuring port 0 and interrogating `app.http.server.shared.localAddress` about the chosen port (fixes #2409).

> Note: Previously, automatic port picking was supported but it was impossible to retrieve the selected port back from Vapor.

2021-02-24 21:25 UTC, 0xTim requested changes
Thanks for this! Few stylistic changes and we're good to go!

2021-02-24 21:25 UTC, 0xTim commented on Tests/VaporTests/ApplicationTests.swift
> +    func testAutomaticPortPickingWorks() throws {
We're moving towards non-throwing tests as XCTest doesn't handle throwing tests very and show the line that threw

2021-02-24 21:25 UTC, 0xTim commented on Tests/VaporTests/ApplicationTests.swift
> +        let res = try app.client.get("http://localhost:\(port ?? 0)/hello").wait()
We should wrap this in an `XCTAssertNoThrow`

2021-02-24 21:25 UTC, 0xTim commented on Tests/VaporTests/ApplicationTests.swift
> +        let port = app.http.server.shared.localAddress?.port
XCTUnwrap should solve the optional port

2021-02-24 21:45 UTC, weissi commented on Tests/VaporTests/ApplicationTests.swift
> +    func testAutomaticPortPickingWorks() throws {
ah cool, yeah, us too, just copied the test case above. will fix.

2021-02-24 21:49 UTC, weissi commented on Tests/VaporTests/ApplicationTests.swift
> +        let port = app.http.server.shared.localAddress?.port
that `throws` though :), rewrote it differently.

2021-02-24 21:50 UTC, weissi commented on Tests/VaporTests/ApplicationTests.swift
> +        let res = try app.client.get("http://localhost:\(port ?? 0)/hello").wait()
got rid of the unnecessary variable

2021-02-25 10:24 UTC, 0xTim approved these changes
Thanks!

2021-02-25 10:24 UTC, merged

2021-02-25 10:24 UTC, tanner0101 commented
These changes are now available in [4.41.0](https://github.com/vapor/vapor/releases/tag/4.41.0)