Fix parsing complex accept headers
vapor/vapor pull request #2603
Opened 2021-04-11 10:59 UTC by schwmi

Fixes #2283

This PR fixes an issue that parsing more complex accept headers like `text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8` failed.
Reason was that during directive parsing the semicolon was parsed in greedy way, preferred over comma. (.e.g parsing the mentioned header would lead to "text/html,application/xhtml+xml,application/xml;q=0.9" as single directive). I fixed that by also considering commas when parsing the next semicolon. 
As this directive parsing code is used also for other header types I am not sure if it suits all other needs, or if some other logic relies on the former behaviour - all existing unit tests still pass (but the test coverage isn't that high)

When adding unit tests for those more complex accept headers I realized that also the logic in `HTTPMediaTypePreference.swift` for comparing two media types is incorrect. I fixed this along the way and also added a test for this

2021-04-11 11:03 UTC, schwmi commented on Sources/Vapor/HTTP/Headers/HTTPMediaTypePreference.swift
> +                return .orderedAscending
This was twisted - as `aq` is the left hand side input parameter the should return  `.orderedDescending` when larger than the right hand side.

2021-04-11 11:03 UTC, schwmi commented on Sources/Vapor/HTTP/Headers/HTTPHeaders+Directive.swift
> +            } else if let separatorMatch = self.firstIndex(matchingAnyOf: .comma, .semicolon) {
Instead of always preferring `semicolon` first we also check if there are `comma` along the way.

2021-04-12 09:45 UTC, 0xTim requested changes
Thanks for doing this! Just a couple of changes around shoring up the tests and we're good to go!

2021-04-12 09:45 UTC, 0xTim commented on Tests/VaporTests/HTTPHeaderTests.swift
> +            headers.replaceOrAdd(name: .accept, value: "text/html")
Just for complete sanity and to avoid future regressions could you add an assert to these tests that ensures that the accepted media types match the ones in the header. E.g.

```swift
XCTAssertTrue(headers.accept.mediaTypes.contains(.html))
```

2021-04-12 10:45 UTC, schwmi commented on Tests/VaporTests/HTTPHeaderTests.swift
> +            headers.replaceOrAdd(name: .accept, value: "text/html")
Thanks for the feedback. I've added some cases + removed the catchall from the second, more complex test to allow testing for concrete types…

2021-04-12 13:01 UTC, 0xTim commented
Original comment:

Fixes #2283

This PR fixes an issue that parsing more complex accept headers like text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8 failed.
Reason was that during directive parsing the semicolon was parsed in greedy way, preferred over comma. (.e.g parsing the mentioned header would lead to "text/html,application/xhtml+xml,application/xml;q=0.9" as single directive). I fixed that by also considering commas when parsing the next semicolon.
As this directive parsing code is used also for other header types I am not sure if it suits all other needs, or if some other logic relies on the former behaviour - all existing unit tests still pass (but the test coverage isn't that high)

When adding unit tests for those more complex accept headers I realized that also the logic in HTTPMediaTypePreference.swift for comparing two media types is incorrect. I fixed this along the way and also added a test for this

2021-04-12 13:01 UTC, 0xTim approved these changes
Thanks!

2021-04-12 13:03 UTC, merged