Added PlaintextDecoder
vapor/vapor pull request #2637
Opened 2021-06-06 08:35 UTC by dirtyhabits97

* Created `PlaintextDecoder` to easily decode raw strings
* Registered `PlaintextDecoder` as the default decoder for `Content-Type: plain/text`

This fixes #2607

2021-06-09 16:37 UTC, 0xTim requested changes

2021-06-09 16:37 UTC, 0xTim commented on Tests/VaporTests/ContentTests.swift
> +            XCTAssertEqual(try res.content.decode(UInt8.self), 255)
Could you add a test that decodes a string as well? Otherwise LGTM

2021-06-10 01:46 UTC, dirtyhabits97 commented on Tests/VaporTests/ContentTests.swift
> +            XCTAssertEqual(try res.content.decode(UInt8.self), 255)
Done. Also added a test case for empty string as the response's body.

2021-06-10 08:57 UTC, 0xTim approved these changes
Thanks! LGTM

2021-06-10 09:07 UTC, 0xTim commented
Original comment:

> * Created PlaintextDecoder to easily decode raw strings
> * Registered PlaintextDecoder as the default decoder for Content-Type: plain/text
> This fixes #2607

2021-06-10 09:09 UTC, merged