Add new reason to empty body validation
vapor/vapor pull request #2642
Opened 2021-06-13 04:30 UTC by rickramirr

2021-06-23 18:34 UTC, calebkleveter approved these changes

2021-06-25 12:23 UTC, siemensikkema commented
@rickramirr Seems like a helpful addition to me 👍🏻 We might as well finish the job and change line 48 to:
```swift
            throw Abort(.unprocessableEntity, reason: "Missing \"Content-Type\" header")
```

2021-06-26 15:48 UTC, rickramirr commented
@siemensikkema Nice idea, i'm adding it

2021-06-29 09:16 UTC, 0xTim requested changes
I'm going to be really annoying and ask for a test to validate the messages being returned

2021-06-30 15:16 UTC, 0xTim approved these changes
LGTM

2021-06-30 15:26 UTC, merged