Resolve issue #2650
vapor/vapor pull request #2674
Opened 2021-08-22 22:30 UTC by paunik

In order to prevent 5xx internal error we try to:

- validate number of parameters in FormDataDecoder so we can detect when only boundary is present.

2021-09-05 20:36 UTC, 0xTim requested changes
Just need to switch the if statement to a guard and we'll be good to go

2021-09-05 20:36 UTC, 0xTim commented on Sources/Vapor/Multipart/FormDataDecoder+Content.swift
> +        if headers.contentType?.parameters.count ?? 1 == 1  {
I'd prefer this to be a guard statement to match the rest of the code and better indicate an early exit. And we can chain the statements to avoid defaulting to 1

2021-09-05 22:29 UTC, paunik commented on Sources/Vapor/Multipart/FormDataDecoder+Content.swift
> +        if headers.contentType?.parameters.count ?? 1 == 1  {
Cool, seems that I had naive assumption that this will be ok, as test was failing when form data are present.
Now I changed if -> guard and moved check lower so we can check if we have anything else apart boundary. If only that in body then we throw.

2022-08-01 09:48 UTC, 0xTim approved these changes
Thanks! @paunik if you could fix the conflicts this can be merged

2023-08-16 04:22 UTC, gwynne approved these changes

2023-08-16 04:26 UTC, merged