Adds default file support to FileMiddleware
vapor/vapor pull request #2678
Opened 2021-09-08 17:18 UTC by NeedleInAJayStack

Many HTTP servers support specifying a default file when a request hits a public directory. For example, a request to `http://server.com/path/` may automatically serve the file at `path/index.html`.

This PR adds this functionality to the FileMiddleware via an initialization parameter. It defaults to disabled but can be customized to whatever default file name is desired. This default file name is also served automatically for all subdirectory queries. If the default file does not exist, the request is passed on to the next Responder.

A usage example:

```swift
// Default file serving is disabled
app.middleware.use(FileMiddleware(publicDirectory: "public/"))

// Serves `index.html` (if it exists) to a request to `http://server.com/`, as well as any subdirectories
app.middleware.use(FileMiddleware(publicDirectory: "public/", defaultFile: "index.html"))
```

Resolves: https://github.com/vapor/vapor/issues/2455

2021-10-30 05:04 UTC, NeedleInAJayStack commented
Hey @0xTim or @gwynne, do you mind giving this a look?

2021-11-24 18:11 UTC, stevapple requested changes
Cases where `defaultFile` starts with `/` should be addressed.
We should either handle such cases explicitly or prohibit them with assertions.

2021-11-24 18:11 UTC, stevapple commented on Sources/Vapor/Middleware/FileMiddleware.swift
> +            defaultFilePath = defaultFilePath + defaultFileName
Ideally we should explicitly handle the cases where `defaultFileName` starts with `/`.
In those cases, `defaultFilePath` should be `publicDirectory + defaultFileName`.

2021-11-24 18:11 UTC, stevapple commented on Tests/VaporTests/FileTests.swift
> +
And there should be a `testDefaultFileFromRoot`.

2021-11-27 16:54 UTC, NeedleInAJayStack commented on Sources/Vapor/Middleware/FileMiddleware.swift
> +            defaultFilePath = defaultFilePath + defaultFileName
Great suggestion! I've added this.

2021-11-27 16:55 UTC, NeedleInAJayStack commented on Tests/VaporTests/FileTests.swift
> +
Sure, I've added a testDefaultFileAbsolute method.

2021-11-27 17:23 UTC, stevapple commented on Sources/Vapor/Middleware/FileMiddleware.swift
> +            defaultFilePath = defaultFilePath + defaultFileName
I think we should allow fallback to an absolute default file whenever the requested path doesn't exist? It doesn't rely on an existing directory as the root.

2021-11-28 00:40 UTC, NeedleInAJayStack commented on Sources/Vapor/Middleware/FileMiddleware.swift
> +            defaultFilePath = defaultFilePath + defaultFileName
> I think we should allow fallback to an absolute default file whenever the requested path doesn't exist?

I considered this and my only hesitation is that file existence is the only means for us to pass through FileMiddleware. If we make an absolute defaultFile and it matches even on paths that don't exist, we are basically saying that the server should ONLY ever serve the public files or the default file, regardless of any other routing definitions.

For example, consider the following server:

```swift
app.middleware.use(FileMiddleware(publicDirectory: "/Public", defaultFile: "/index.html"))
app.routes.get("hello") { req in
    return "hello there".encodeResponse(for: req)
}
```

We would never be able to reach the `hello` route because it would be caught in the FileMiddleware and `index.html` would be served.

Perhaps this is okay or there's a better way to do this, but I don't have enough experience with Vapor's Middleware system to know for sure. I'd be really interested in your opinion!

2021-12-06 08:32 UTC, stevapple approved these changes

2021-12-06 08:32 UTC, stevapple commented on Sources/Vapor/Middleware/FileMiddleware.swift
> +            newPath = String(newPath.dropFirst())
```suggestion
            newPath.removeFirst()
```

2021-12-06 08:34 UTC, stevapple commented
I’m okay with the change, cc @0xTim

2021-12-06 16:49 UTC, 0xTim approved these changes

2021-12-06 17:09 UTC, merged