Filled in missing documentation in commonly used APIs
vapor/vapor pull request #2737
Opened 2021-11-14 21:48 UTC by Joannis

I've added documentation for some of the most commonly used Vapor APIs that were still missing doc comments.

2021-11-15 05:41 UTC, gwynne requested changes
Just some grammatical and phrasing nits. I make no warranty that any of the suggestions are indisputably improvements in any given person's eyes, not even my own 😉.

2021-11-15 05:41 UTC, gwynne commented on Sources/Vapor/Application.swift
> +    /// Starts the Application using the `start()` command, then waits for any running tasks to complete
I would say "method" rather than "command" here.

2021-11-15 05:41 UTC, gwynne commented on Sources/Vapor/Application.swift
> +    /// Under normal circumstances, `run `will start the shut down and wait for the web server to (manually) shut down before exiting the application.
```suggestion
    /// Under normal circumstances, `run() `will begin the shutdown, then wait for the web server to (manually) shut down before returning.
```
(Yes, the use of both "shut down" and "shutdown" is on purpose 😅)

2021-11-15 05:41 UTC, gwynne commented on Sources/Vapor/Request/Request.swift
> +    /// If no ContentDecoder is provided, a supported Decoder will be selected based on the Request's Content-Type header.
```suggestion
    /// This container is used to read your `Decodable` type using a `ContentDecoder` implementation.
    /// If no `ContentDecoder` is provided, the `Request`'s `Content-Type` header is used to look up a decoder registered for that type.
```

2021-11-15 05:41 UTC, gwynne commented on Sources/Vapor/Request/Request.swift
> +    /// If you cannot ensure that a library returns on this EventLoop, you can use `eventLoopFuture.hop(to: request.eventLoop)`
```suggestion
    /// The `EventLoop` which is handling this request. The route handler and any relevant middleware are invoked on this event loop.
    /// 
    /// - Warning: A futures-based route handler **MUST** return an `EventLoopFuture` bound to this event loop.
    ///   If this is difficult or awkward to guarantee, use `EventLoopFuture.hop(to:)` to jump to this event loop.
```

2021-11-16 02:19 UTC, 0xTim requested changes
Couple of minor nits then we're good

2021-11-16 02:19 UTC, 0xTim commented on Sources/Vapor/Client/Client.swift
> +    }`
Random backtick 
```suggestion
    }
```

2021-11-16 02:19 UTC, 0xTim commented on Sources/Vapor/Application.swift
> +    /// Starts the Application using the `start()` command, then waits for any running tasks to complete
Agree, we don't have a start command so that could be seen as confusing

2021-11-16 13:50 UTC, 0xTim approved these changes

2021-11-16 18:05 UTC, merged