Update `Response` inline comments
vapor/vapor pull request #2756
Opened 2022-01-05 17:36 UTC by 0xTim

2022-01-06 17:09 UTC, stevapple requested changes

2022-01-06 17:09 UTC, stevapple commented on Sources/Vapor/Response/Response.swift
>      /// represents the `HTTPBody`.
```suggestion
    /// represents the `Body`.
```

2022-01-06 17:09 UTC, stevapple commented on Sources/Vapor/Response/ResponseCodable.swift
> +    /// - returns: An `Response`.
```suggestion
    /// - returns: A `Response`.
```

2022-01-06 17:09 UTC, stevapple commented on Sources/Vapor/Response/Response.swift
> +    /// Get and set `HTTPCookies` for this `Response`
```suggestion
    /// Get and set `HTTPCookies` for this `Response`.
```

2022-01-06 19:11 UTC, Joannis approved these changes
As soon as @stevapple 's comments are resolved, I'm good 👍

2022-01-07 15:27 UTC, stevapple approved these changes
LGTM now👍

2022-01-07 15:47 UTC, 0xTim commented
No code changes and not critical docs, so we'll roll this out in the next release

2022-01-07 15:47 UTC, merged