Added custom failure description
vapor/vapor pull request #2804
Opened 2022-04-14 03:57 UTC by AndreYonadam

This PR adds support for custom failure descriptions. This solves two major issues, unreadable keys and the ability to provide localized failure descriptions for each Validation.

2022-04-14 09:55 UTC, 0xTim requested changes
Thanks for this, looks great! One change needed to avoid a breaking change then good to go

2022-04-14 09:55 UTC, 0xTim commented on Sources/Vapor/Validation/Validation.swift
> +    public let customFailureDescription: String?
We're changing the public API here so will need a new `init()` that matches the existing behaviour to avoid any breaking changes

2022-04-15 05:35 UTC, AndreYonadam commented on Sources/Vapor/Validation/Validation.swift
> +    public let customFailureDescription: String?
Done! Let me know if there are any other changes you'd like.

2022-04-15 09:28 UTC, 0xTim approved these changes
LGTM!

2022-04-15 09:29 UTC, 0xTim commented
Original comment:
This PR adds support for custom failure descriptions. This solves two major issues, unreadable keys, and the ability to provide localized failure descriptions for each Validation.

2022-04-15 09:36 UTC, merged