Added async route test capability
vapor/vapor pull request #2805
Opened 2022-04-14 05:56 UTC by AndreYonadam

2022-04-14 09:50 UTC, 0xTim requested changes
So whilst I agree these changes make sense in an async world this is going to be confusing to people porting code over, not to mention the compiler (did you have to change the existing tests to get it to compile?). So these functions should all return `XCTApplicationTester` like the non-async versions, unless you make an async version of `sendRequest`. The `beforeRequest` and `afterResponse` closures should just become async

2022-04-15 05:37 UTC, AndreYonadam commented
> So whilst I agree these changes make sense in an async world this is going to be confusing to people porting code over, not to mention the compiler (did you have to change the existing tests to get it to compile?). So these functions should all return `XCTApplicationTester` like the non-async versions, unless you make an async version of `sendRequest`. The `beforeRequest` and `afterResponse` closures should just become async

I didn't have to change the existing tests to get it to compile. I only did so to ensure that the new code was being tested/used somewhere. I am fine with either providing an async version of `sendRequest` or simply just changing the `beforeRequest` and `afterResponse` closures should just become async instead of this change. I feel like you might prefer the latter?

2022-04-15 09:41 UTC, 0xTim commented
So I think we need both essentially. There are 3 helper functions in XCTVapor including a `sendRequest` - https://github.com/vapor/vapor/blob/main/Sources/XCTVapor/XCTApplication.swift#L157

So essentially just 3 additional functions that match these but with closures that can run async code - make sense?

2022-04-17 09:15 UTC, 0xTim approved these changes
Thanks!

2022-04-17 09:20 UTC, merged