Support for peerAddress on Request
vapor/vapor pull request #2822
Opened 2022-05-11 22:22 UTC by paunik

MR for https://github.com/vapor/vapor/issues/2736

- Added computed property peerAddress on Request class that parses headers commonly used by proxies and load balancers to pass through originating client address
- Added tests for peerAddress computed property

2022-05-12 06:54 UTC, Joannis commented on Sources/Vapor/Request/Request.swift
> +    public var peerAddress: String? {
I like your docs! But it also made me realise that the different formats for these headers should be mixed carefully. I think it's wiser to expose `peerAddress` as a `SocketAddress`, and try to parse that address from these headers. Possibly providing a fallback for the port, and if there are multiple IP addresses, dealing with that in a later PR or returning a SocketAddress based on the client_IP from your examples.

2022-05-12 07:43 UTC, Joannis commented
@0xTim can you read my above comment?

2022-05-12 09:19 UTC, paunik commented on Sources/Vapor/Request/Request.swift
> +    public var peerAddress: String? {
Hey, tnx for the reply, while I was working i had exact taught, that maybe should be "unified" how this address is returned, rather then just some string :)

From my side makes 100% sense to have this as `SocketAddress`

2022-05-13 08:45 UTC, paunik commented on Sources/Vapor/Request/Request.swift
> +    public var peerAddress: String? {
@Joannis If I want to use `SocketAddress` as return, and from forwarded header and from xForwardedFor I can only get the address and not the port, what would be ok value to use for `SocketAddress(address: String, port: Int)` init method?

2022-05-17 16:12 UTC, 0xTim commented on Sources/Vapor/Request/Request.swift
> +    public var peerAddress: String? {
I agree `SocketAddress` makes sense, we want to try and avoid `String` where possible. For the port a sensible fallback I guess is port 80

2022-05-19 08:22 UTC, paunik commented on Sources/Vapor/Request/Request.swift
> +    public var peerAddress: String? {
👍

2022-05-19 08:32 UTC, Joannis commented on Sources/Vapor/Request/Request.swift
> +    public var peerAddress: String? {
Sorry that I missed your reply last week @paunik . I was going to suggest exactly what Tim did

2022-05-20 21:20 UTC, paunik commented on Sources/Vapor/Request/Request.swift
> +    public var peerAddress: String? {
Done, only doubt is about this test: `testRequestPeerAddressRemoteAddres` where i dont check that the port itself is different then 80, but not sure if we really need that test?

2022-05-21 07:36 UTC, Joannis approved these changes

2022-05-21 07:36 UTC, Joannis commented
Thanks for the PR, and your work to improve upon the feedback! LGTM!

2022-05-21 07:36 UTC, Joannis commented
I'll await @0xTim 's feedback as well, so he can merge it.

2022-05-23 09:51 UTC, 0xTim commented
Original comment

MR for https://github.com/vapor/vapor/issues/2736

- Added computed property peerAddress on Request class that parses headers commonly used by proxies and load balancers to pass through originating client address
- Added tests for peerAddress computed property

2022-05-23 09:54 UTC, 0xTim requested changes
We can't force try anywhere in the framework, we should change this

2022-05-23 09:54 UTC, 0xTim commented on Sources/Vapor/Request/Request.swift
> +            return try! SocketAddress.init(ipAddress: clientAddress, port: 80)
We should not be force trying these. Since `peerAddress` is optional, make these `try?`

2022-05-23 09:54 UTC, 0xTim commented on Sources/Vapor/Request/Request.swift
> +            return try! SocketAddress.init(ipAddress: xForwardedFor, port: 80)
As above

2022-05-24 22:06 UTC, paunik commented on Sources/Vapor/Request/Request.swift
> +            return try! SocketAddress.init(ipAddress: clientAddress, port: 80)
Done, tnx.

2022-05-24 22:06 UTC, paunik commented on Sources/Vapor/Request/Request.swift
> +            return try! SocketAddress.init(ipAddress: xForwardedFor, port: 80)
Done

2022-05-26 11:03 UTC, 0xTim commented on Sources/Vapor/Request/Request.swift
> +            return try? SocketAddress.init(ipAddress: clientAddress, port: 80)
Actually, we don't need to provide a port here since it's optional so we can probably just leave it out. That should result with the peer address just being an IP address right?

2022-05-26 21:25 UTC, paunik commented on Sources/Vapor/Request/Request.swift
> +            return try? SocketAddress.init(ipAddress: clientAddress, port: 80)
Thing is that SocketAddress init has port as Int, and not Int? so it cant be omitted. Guess we are stuck with default port, and in this case 80 as suggested.

2022-05-27 18:53 UTC, Joannis commented on Sources/Vapor/Request/Request.swift
> +            return try? SocketAddress.init(ipAddress: clientAddress, port: 80)
I think we can merge, right @0xTim ?

2022-05-30 10:16 UTC, 0xTim commented on Sources/Vapor/Request/Request.swift
> +            return try? SocketAddress.init(ipAddress: clientAddress, port: 80)
I was looking at the `SocketAddress` in Soto 🤦 

Yes we're good to merge, will bundle it in with a few other PRs

2022-05-30 10:17 UTC, 0xTim approved these changes

2022-06-06 07:00 UTC, merged