Bug/multipart chinese error
vapor/vapor pull request #2826
Opened 2022-05-16 11:26 UTC by BennyDeBock

Adds a case to ContentDisposition to be compliant with [rfc-5987](https://www.rfc-editor.org/rfc/rfc5987). This allows handling of unicode and other format characters in filenames.

closes #2802

2022-05-16 12:05 UTC, 0xTim requested changes
It would be good to add a test to make sure we don't break it again in the future if possible

2022-05-16 15:08 UTC, BennyDeBock commented on Tests/VaporTests/ContentTests.swift
> +            image: File(data: "<contents of image>", filename: "UTF-8\'\'%E5%A5%B9%E5%9C%A8%E5%90%83%E6%B0%B4%E6%9E%9C.png")
no, as we (according to the implementation and what we read in the `rfc`) are overriding the `filename` variable with the `filename*`. Hence we expect the `UTF-8` string given by the incoming request as the filename

2022-05-17 08:41 UTC, 0xTim approved these changes
🎉

2022-05-17 08:42 UTC, merged

2022-05-17 08:56 UTC, OrToR-KJM commented
내 Galaxy에서 보냄
-------- 원본 이메일 --------발신: Vapor Bot ***@***.***> 날짜: 22/5/17  17:42  (GMT+09:00) 받은 사람: vapor/vapor ***@***.***> 참조: Subscribed ***@***.***> 제목: Re: [vapor/vapor] Fix handling unicode characters in multipart filenames (PR #2826) 
These changes are now available in 4.59.1

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>