Move to from `Lock` to `NIOLock`
vapor/vapor pull request #2891
Opened 2022-10-04 08:50 UTC by MahdiBM

`Lock` has recently been deprecated in favor of `NIOLock`.

### Changes
All `Lock`s have been renamed to `NIOLock`.
`Application` now has two new properties named `nioLocks` & `nioSync`, and `locks` & `sync` have been marked as deprecated.

Feel free to suggest better names for `nioLocks` and `nioSync`.

2022-10-04 09:10 UTC, MahdiBM commented
The test failures seem real, but also unrelated to this PR.
`ServerTests.testConfigureHTTPDecompressionLimit` seems to consistently fail. Perhaps due to a change in NIO?

2022-10-04 12:04 UTC, MahdiBM commented
https://github.com/vapor/vapor/issues/2892

2022-10-13 16:15 UTC, 0xTim requested changes
I don't think we need to change any of the names of the application properties since they're namespaced under `Application`

2022-10-13 16:23 UTC, MahdiBM commented on Sources/Vapor/Application.swift
> +    public final class NIOLocks {
can you elaborate more please?
there is rule where if public properties are name-spaced under another public property, we can make breaking changes to them?!
or do you mean I could have fit `NIOLock` stuff under the same `Locks` class?

2022-10-13 16:25 UTC, 0xTim commented on Sources/Vapor/Application.swift
> +    public final class NIOLocks {
We only need to change the deprecated types (so `Lock` to `NIOLock`) rather than renaming everything that refers to them

2022-10-13 16:41 UTC, MahdiBM commented on Sources/Vapor/Application.swift
> +    public final class NIOLocks {
thats news to me from what I understand ... would this new commit fix the problem?

2022-10-13 16:47 UTC, 0xTim requested changes
Yep this is looking good! Once last change then good to go

2022-10-13 16:47 UTC, 0xTim commented on Sources/Vapor/Application.swift
> -        self.locks = .init()
Let's move this back to reduce the change and make it easier to work out where it's created

2022-10-13 16:47 UTC, 0xTim commented on Sources/Vapor/Application.swift
> +    public var locks = Locks()
Revert

2022-10-13 16:47 UTC, 0xTim commented
Original Comment:
`Lock` has recently been deprecated in favor of `NIOLock`.

### Changes
All `Lock`s have been renamed to `NIOLock`.
`Application` now has two new properties named `nioLocks` & `nioSync`, and `locks` & `sync` have been marked as deprecated.

Feel free to suggest better names for `nioLocks` and `nioSync`.

2022-10-13 16:50 UTC, MahdiBM commented on Sources/Vapor/Application.swift
> +    public var locks = Locks()
👍 has to do it before to avoid deprecation warnings

2022-10-13 16:55 UTC, 0xTim approved these changes
Thanks!

2022-10-13 17:09 UTC, merged

2022-11-15 16:01 UTC, 0xTim commented
Ah that's a good point. Unfortunately we've now released so there's not a huge amount to do. I'm surprised this didn't get picked up by the API Checker

2022-11-15 16:25 UTC, MahdiBM commented
In my defense, i did realize this, and that was why i sound surprised in one of the comments above 😶

2022-11-15 16:29 UTC, ffried commented
> It didn't get picked up because we didn't configure the API breakage check to run for this repo until two weeks later 🤦‍♀️
Perfect timing... 😂 

> In my defense, i did realize this, and that was why i sound surprised in one of the comments above 😶

I'm not blaming anyone here. Stuff like this happens. 😉 
My intention here was to simply document this. It only affected internal playground-code of mine and also fixing it is rather easy. No big deal IMHO.