Make Services in Vapor Usable
vapor/vapor pull request #2901
Opened 2022-10-20 11:51 UTC by 0xTim

This adds real support to Vapor to make it easy to integrate different services that can be tested.

For example, if you have a service defined as:

```swift
protocol MyService {
    func `for`(_ request: Request) -> MyService
    func doSomething() -> String
}
```

You may then have a real implementation:

```swift

import Vapor

struct MyRealService: MyService {
    let logger: Logger
    let eventLoop: EventLoop
    
    func `for`(_ request: Vapor.Request) -> MyService {
        return MyRealService(logger: request.logger, eventLoop: request.eventLoop)
    }
    
    func doSomething() -> String {
        return "Tada"
    }
    
}
```

This is a very contrived example, but shows a service that needs a `Logger` and `EventLoop` - things that are normally tied to specific requests.

2022-10-20 13:10 UTC, 0xTim commented
One point for comment is it might be worth defaulting to making service access `async` to avoid immediately deprecating everything when #2873 lands

2022-10-21 00:58 UTC, Andrewangeta approved these changes

2022-10-27 08:18 UTC, Joannis requested changes

2022-10-27 08:18 UTC, Joannis commented on Tests/VaporTests/ServiceTests.swift
> +
Nit, but there's a lot of whitespace changes.

2022-10-27 08:18 UTC, Joannis commented on Sources/Vapor/Services/Service.swift
> +            public init(_ run: @escaping (Application) -> ()) {
Shouldn't we mark these `@Sendable` from now on?

2022-10-27 08:18 UTC, Joannis commented on Sources/Vapor/Services/Service.swift
> +        public func use(_ makeService: @escaping (Application) -> ServiceType) {
`@Sendable`?

2022-10-27 08:18 UTC, Joannis commented on Sources/Vapor/Services/Service.swift
> +                self.initialize()
I know this works fine, but can we make `initialize()` return the newly created entity? Then return that here.

2022-10-27 08:18 UTC, Joannis commented on Sources/Vapor/Services/Service.swift
> +    struct Service<ServiceType> {
`public struct` instead of `public extension`? I tend to be explicit in marking things public in libraries/frameworks, so future changes don't accidentally expose internal API.

2022-10-27 08:18 UTC, Joannis commented
Great addition btw!

2022-12-18 17:55 UTC, FullQueueDeveloper commented
@0xTim @Joannis @Andrewangeta What's the best way I can help get this merged? 

1. I'm using this code in a project
2. Tim has copy-pasted this into Discord at least three times

2023-01-27 22:12 UTC, Joannis commented
What's the goal of this PR?

2023-01-27 23:12 UTC, 0xTim commented
@Joannis what do you mean?

2023-02-16 10:49 UTC, Joannis commented
@0xTim sorry for missing your message;
I mean, what's the intention behind this new feature? To make it easier to work with `app.storage`? Or is there another goal?

2024-12-13 08:09 UTC, dimitribouniol approved these changes

2024-12-16 17:56 UTC, merged

2025-03-30 12:29 UTC, mynona commented
Would it be possible to add this changed approach to the vapor documentation?

2025-04-01 14:15 UTC, 0xTim commented
@mynona yeah its on the list, PRs would be great!