HTTPServerErrorHandler: Improve Error Handling for HTTPParserError
vapor/vapor pull request #2922
Opened 2022-11-29 08:59 UTC by fred-sch

Invalid HTTP previously just closed the connection, but did not actually handle the errors. 

This PR uses an adapted version of https://github.com/apple/swift-nio/blob/main/Sources/NIOHTTP1/HTTPServerProtocolErrorHandler.swift to properly catch exceptions if they occur.

Closes: https://github.com/vapor/vapor/issues/2921

2022-11-29 09:44 UTC, MrSkwiggs commented on Sources/Vapor/HTTP/Server/HTTPServer.swift
> +        // HTTP error response if another response hasn't started yet.
I'm not sure we want to use this tone of voice in code comments / docs
```suggestion
        // Any HTTPParserError is automatically fatal, and we don't actually need (or want) to
        // provide that error to the client: we just want to inform them something went wrong and then
        // let the rest of the pipeline close. However, we can only send an
        // HTTP error response if another response hasn't started yet.
```

2022-11-29 12:56 UTC, fred-sch commented on Sources/Vapor/HTTP/Server/HTTPServer.swift
> +        // HTTP error response if another response hasn't started yet.
@MrSkwiggs thanks for having a look at the PR.

I actually took this comment directly from https://github.com/apple/swift-nio/blob/00341c92770e0a7bebdc5fda783f08765eb3ff56/Sources/NIOHTTP1/HTTPServerProtocolErrorHandler.swift#L41, but I think it is perfectly fine to adapt to Vapors code/documentation style.

2022-11-29 13:03 UTC, fred-sch commented on Sources/Vapor/HTTP/Server/HTTPServer.swift
> +            context.fireErrorCaught(error)
@MrSkwiggs do you agree that `context.fireErrorCaught(error)` should always be called (to propagate the error through the ChannelPipeline) instead of just closing it with `context.close(mode: .output, promise: nil)`?

Also I was thinking that a line for the logger would be nice in this guard statement:
```swift
self.logger.debug("Catching HTTP server error: \(error)")
```

2022-11-29 13:10 UTC, MrSkwiggs commented on Sources/Vapor/HTTP/Server/HTTPServer.swift
> +        // HTTP error response if another response hasn't started yet.
Huh interesting 😅

2022-11-29 13:29 UTC, MrSkwiggs commented on Sources/Vapor/HTTP/Server/HTTPServer.swift
> +            context.fireErrorCaught(error)
I can't speak for Vapor as I was just merely glancing at your PR and am not a maintainer here; but I would think so yes, though take whatever I say with a healthy spoonful of salt :d

2022-12-12 08:55 UTC, fred-sch commented
Could you have a look at the proposed changes and trigger the workflow when you have some time @0xTim ?

2023-01-14 11:14 UTC, Joannis commented on Sources/Vapor/HTTP/Server/HTTPServer.swift
> +        // Otherwise the "general fix" would brake the `testRequestBodyStreamGetsFinalisedEvenIfClientDisappears`
brake -> break?

2023-01-14 11:14 UTC, Joannis commented on Sources/Vapor/HTTP/Server/HTTPServer.swift
> +    private var hasUnterminatedResponse: Bool = false
Is this being set anywhere?

2023-01-17 13:52 UTC, fred-sch commented on Sources/Vapor/HTTP/Server/HTTPServer.swift
> +    private var hasUnterminatedResponse: Bool = false
You are absolutely write this was not being set anywhere. It is now correctly being set in `func write(context: ChannelHandlerContext, data: NIOAny, promise: EventLoopPromise<Void>?)`.

2023-01-17 13:59 UTC, fred-sch commented
I had another look at the code and figured out that I was most likely not adding the `HTTPServerErrorHandler` at the right place between the different `ChannelHandler`s (which lead to some problems).

Now I put the `HTTPServerErrorHandler` always before the  `HTTPServerResponseEncoder`. Also, I added the `NIOCloseOnErrorHandler` at the very end of the `ChannelHandlers`. This one should now take care of the role the `HTTPServerErrorHandler` had previously (closing connections) while the `HTTPServerErrorHandler` takes care of `HTTPParserError`s.

Can one of you possibly take another look at the changes @Joannis @0xTim ?

2023-02-23 15:18 UTC, fred-sch commented
For the context again: If a vapor app is supporting HTTP without TLS/SSL and is running behind nginx proxy, a single faulty (invalid HTTP) request can easily bring down all upstream servers  for a time amount of the upstreams `fail_timeout` if the app is under some load, because there is also a bug in nginx that it will ignore the `proxy_next_upstream_tries` directive if under load (compare: https://trac.nginx.org/nginx/ticket/2421). 

Another side note: we have been using this fix on one of our vapor based apis (approx. 20 Million req/day) for over a month now and have not experienced any problems so far. 

Any thoughts or suggestions on this MR are very appreciated!

2023-03-01 10:41 UTC, 0xTim reviewed
This looks good to me - @Lukasa @weissi are you able to give this a quick once over to ensure the handler stuff is being used correctly?

2023-03-02 17:02 UTC, fred-sch commented on Sources/Vapor/HTTP/Server/HTTPServer.swift
> +            let head = HTTPResponseHead(version: .http1_1, status: .badRequest, headers: headers)
Maybe the easiest way to deal with this would be to have a separate `HTTP1ServerErrorHandler`and `HTTP2ServerErrorHandler` that are added in `addVaporHTTP1Handlers` and `addVaporHTTP2Handlers` respectively?

As far as I understand getting the HTTP version from the current request will not be easily possible because the error is thrown in the `feedInput` method of the `BetterHTTPParser`  when the `HTTPRequestDecoder` is used to transform the InboundIn `ByteBuffer` to the InboundOut `HTTPServerRequestPart` (in the Http1 pipeline). So we never actually get to see the `HTTPServerRequestPart` when an error is thrown.

I am also wondering if this is even possibly happening in the HTTP/2 pipeline, because the `HTTP2FramePayloadToHTTP1ServerCodec` transforms a `HTTP2Frame.FramePayload` to a `HTTPServerRequestPart`. The only errors that are being thrown on the way should be `NIOHTTP2Errors`, so maybe a separate handler would be needed to handle such errors as well?

2023-03-07 15:32 UTC, 0xTim commented on Sources/Vapor/HTTP/Server/HTTPServer.swift
> +            let head = HTTPResponseHead(version: .http1_1, status: .badRequest, headers: headers)
Yeah that makes sense. @FranzBusch I'd like to ask your thoughts here as the resident NIO expert! And if you have chance for a once-over in general as well that would be ace. This has been running fine in a prod system so I'm happy with the overall stability but just a sanity check to make sure we're not doing anything silly

2023-04-27 09:08 UTC, FranzBusch commented on Sources/Vapor/HTTP/Server/HTTPServer.swift
> +            let head = HTTPResponseHead(version: .http1_1, status: .badRequest, headers: headers)
This PR is by itself fine and writing out a `badRequest` in response to seeing an `HTTPParserError` is good. As you noted above though you also need to handle the `HTTP2Error`s somewhere. Either in a separate handler or by modifying this one.

2023-04-27 12:45 UTC, Lukasa commented on Sources/Vapor/HTTP/Server/HTTPServer.swift
> +            context.fireErrorCaught(error)
What handler is going to deal with these errors?

2023-06-12 14:48 UTC, fred-sch commented on Sources/Vapor/HTTP/Server/HTTPServer.swift
> +            context.fireErrorCaught(error)
Currently the `NIOCloseOnErrorHandler` will eventually close the `Channel`

2023-07-26 11:04 UTC, gwynne requested changes
My only comment here is the one where I resurrected someone else's old comment 😅 But other than that, LGTM

2023-07-26 11:04 UTC, gwynne commented on Sources/Vapor/HTTP/Server/HTTPServer.swift
> +        // HTTP error response if another response hasn't started yet.
While I may be a bit late to the table, NIO is never shy about accepting improvements of this sort, and Vapor isn't either; the suggested rephrasing is a definite improvement.

2023-07-26 14:28 UTC, fred-sch commented on Sources/Vapor/HTTP/Server/HTTPServer.swift
> +        // HTTP error response if another response hasn't started yet.
I adjusted the comment as suggested

2023-07-26 14:31 UTC, fred-sch commented on Sources/Vapor/HTTP/Server/HTTPServer.swift
> +            let head = HTTPResponseHead(version: .http1_1, status: .badRequest, headers: headers)
Any opinions on my above comment @0xTim @FranzBusch ?

2023-09-22 07:08 UTC, gwynne commented
@fred-sch Slightly off-topic, is it intentional that the Vapor CI workflows are being run in your fork? (Such as the API docs CI, although it fails immediately since the credentials secrets obviously aren't available.)

2023-09-22 07:09 UTC, gwynne approved these changes
This LGTM at this point, though I wouldn't mind at least one more set of eyes on it.

2023-09-22 12:24 UTC, 0xTim approved these changes
I think we're good to merge!

2023-09-22 13:08 UTC, merged