back deploy concurrency to macOS 10.15
vapor/vapor pull request #2926
Opened 2022-12-12 14:15 UTC by sevki

preceded by https://github.com/vapor/async-kit/pull/97

2022-12-16 13:19 UTC, sevki commented
ping @weissi

2022-12-16 13:20 UTC, weissi commented on Package.swift
> +// swift-tools-version: 5.5.2
```suggestion
// swift-tools-version:5.5.2
```

2022-12-22 13:12 UTC, 0xTim requested changes
Could you enable backporting for all Apple Platforms?

2022-12-22 13:12 UTC, 0xTim commented on Package.swift
> +        .package(url: "https://github.com/apple/swift-nio.git", from: "2.44.0"),
Could you also update async kit to 1.15.0?

2022-12-22 13:12 UTC, 0xTim commented on Sources/Development/routes.swift
> +    @available(macOS 10.15, iOS 15, watchOS 8, tvOS 15, *)
We should enable back porting for all Apple Platforms

2023-01-06 11:31 UTC, sevki commented
Happy new year 🥳 @0xTim! 

Would you mind taking another look?

2023-01-06 13:33 UTC, 0xTim commented
Original comment: 

> preceded by https://github.com/vapor/async-kit/pull/97

2023-01-06 13:35 UTC, 0xTim approved these changes
Thanks!

2023-01-06 14:00 UTC, merged