feature: Adds 308 redirect and docs
vapor/vapor pull request #2934
Opened 2023-01-10 20:11 UTC by NeedleInAJayStack

This adds a 308 redirect to support POST method redirection. This is important because not all user-agents preserve the method and body through a 301 redirect: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/301

2023-01-11 03:25 UTC, NeedleInAJayStack commented
The failing test indicates that this changes the public API. That's true - it adds an additional case to the public `RedirectType` enum.

2023-01-11 09:53 UTC, 0xTim commented
Yeah this is going to be one we can't accept for now as it's a breaking change. We'll need to find another way around it, like adding a new enum and function and deprecate the old stuff

2023-01-12 04:46 UTC, NeedleInAJayStack commented
@0xTim Totally fair point. I've adjusted this so that it introduces a new `Redirect` enum and a `redirectTo` function, and deprecates the existing `RedirectType` enum and `redirect` functions.

2023-01-12 08:43 UTC, Joannis commented
Assuming we want to implement this change, simply replacing an enum (because of breaking changes) with a new enum is only going to expand our problems with the API surface. The only real option in my eyes is to make it a `struct` with a `private enum` of some sorts. That way we can expand the API without breaking the API surface of the enum.

2023-01-13 05:53 UTC, NeedleInAJayStack commented
@Joannis I like your suggestion. I've adjusted the implementation to use a `struct` that wraps an `enum`.

2023-01-18 12:07 UTC, Joannis requested changes

2023-01-18 12:07 UTC, Joannis commented on Tests/VaporTests/ClientTests.swift
> -            $0.redirect(to: "foo")
We can't just change the tests to use the new method. We should be testing the 'old' method in addition to the new one.

2023-01-18 12:07 UTC, Joannis commented on Tests/VaporTests/ClientTests.swift
> -            $0.redirect(to: "foo")
There are 2 other tests that also need to be reverted/duplicated for the new method.

2023-01-26 23:58 UTC, NeedleInAJayStack commented on Tests/VaporTests/ClientTests.swift
> -            $0.redirect(to: "foo")
As far as I can tell, these tests are not really testing the functionality of the redirect itself. Rather, they are testing that changes to a Client configuration have the expected impact based on where the changes occur. The redirect is simply an easy way to test these configuration changes. I definitely can create duplicate test functions, but it seems a little strange to do so for a test that is not really directly testing the redirect behavior.

This does surface that we were not directly testing the `Request.redirect` functionality, so I added those tests for the new and deprecated versions.

2023-01-30 13:44 UTC, Joannis approved these changes
LGTM, awaiting @0xTim 's review

2023-02-16 10:48 UTC, Joannis commented
Ping @0xTim

2023-03-07 00:23 UTC, 0xTim requested changes
This looks in pretty good shape. Want to discuss the API though, suggested what I think is a better replacement

2023-03-07 00:23 UTC, 0xTim commented on Sources/Vapor/Error/Abort.swift
> +    public static func redirectTo(_ location: String, type: Redirect = .normal) -> Abort {
Have to say I'm not a fan of the new API - how about
```suggestion
    public static func redirect(to location: String, redirectType: Redirect = .normal) -> Abort {
```
Fits better with the Swift API guidelines, looks better and makes the redirect type clearer

2023-03-07 04:12 UTC, NeedleInAJayStack commented on Sources/Vapor/Error/Abort.swift
> +    public static func redirectTo(_ location: String, type: Redirect = .normal) -> Abort {
I prefer this too, the only issue is that if we keep around the deprecated `redirect(to, type)`, then when using the default `redirectType` argument, the call is ambiguous. That is, calling `request.redirect(to: "/")`, it wouldn't know whether it was the old `redirect(to, type)` or the new `redirect(to, redirectType)`, and will throw a compilation error.

2023-03-07 06:35 UTC, 0xTim commented on Sources/Vapor/Error/Abort.swift
> +    public static func redirectTo(_ location: String, type: Redirect = .normal) -> Abort {
We can actually be clever/sneaky here - the old API doesn't need a default value. That migrates everyone to the new API unless they're specifying a redirect type without a breaking change

2023-03-07 21:55 UTC, NeedleInAJayStack commented on Sources/Vapor/Error/Abort.swift
> +    public static func redirectTo(_ location: String, type: Redirect = .normal) -> Abort {
Ohhh, that's so smart! I love it! I've made this change

2023-03-08 01:13 UTC, 0xTim requested changes
Great! Just a couple of documentation changes then we're good!

2023-03-08 01:13 UTC, 0xTim commented on Sources/Vapor/Error/Abort.swift
> +    public static func redirect(to location: String, redirectType: Redirect = .normal) -> Abort {
This needs DocC comments for the return type and parameters

2023-03-08 01:13 UTC, 0xTim commented on Sources/Vapor/Error/Abort.swift
>      /// Defaulting to non-permanent to prevent unexpected caching.
If you could tweak this comment to add parameters and return type that would be awesome!

2023-03-08 01:41 UTC, NeedleInAJayStack commented on Sources/Vapor/Request/Redirect.swift
>      /// Defaulting to non-permanent to prevent unexpected caching.
Done

2023-03-08 01:41 UTC, NeedleInAJayStack commented on Sources/Vapor/Request/Redirect.swift
> +    /// Defaulting to non-permanent to prevent unexpected caching.
Done

2023-03-08 01:41 UTC, NeedleInAJayStack commented on Sources/Vapor/Error/Abort.swift
>      /// Defaulting to non-permanent to prevent unexpected caching.
Done

2023-03-08 01:41 UTC, NeedleInAJayStack commented on Sources/Vapor/Error/Abort.swift
> +    public static func redirect(to location: String, redirectType: Redirect = .normal) -> Abort {
Done

2023-03-08 09:40 UTC, 0xTim approved these changes
🙌

2023-03-08 09:42 UTC, merged