Expose Vapor Request's request-id value, so that it can be passed into logging from other libraries
vapor/vapor pull request #2964
Opened 2023-02-21 14:47 UTC by Joannis

Libraries such as Fluent, MySQL, Postgres, MongoKitten & Redis currently have their own logging set up using swift-log. However, it can be useful to see the request-id from which a query was launched. Therefore I propose exposing the request-id as a property on `Request` so that end-users can set the metadata in other libraries' loggers as well. Therefore improving the debugability using these logs.

2023-02-21 14:48 UTC, Joannis commented
See https://github.com/orlandos-nl/MongoKitten/issues/300

2023-02-23 15:02 UTC, 0xTim approved these changes
Thanks! This should get reused when it comes to tackling tracing as well

2023-02-23 15:03 UTC, 0xTim requested changes
Actually I'm going to be a real pain here - can you just add a simple test to make 2 requests and ensure the IDs are different? That'll protect us in the future for any changes and stop silly mistakes

2023-02-24 13:45 UTC, 0xTim commented on Sources/Vapor/HTTP/Server/HTTPServerResponseEncoder.swift
> +            }
Indentation
```suggestion
        }
```

2023-02-24 13:46 UTC, 0xTim commented
Original comment:
> Libraries such as Fluent, MySQL, Postgres, MongoKitten & Redis currently have their own logging set up using swift-log. However, it can be useful to see the request-id from which a query was launched. Therefore I propose exposing the request-id as a property on `Request` so that end-users can set the metadata in other libraries' loggers as well. Therefore improving the debugability using these logs.

2023-02-24 14:38 UTC, merged