Better `DecodingError` description
vapor/vapor pull request #2969
Opened 2023-03-01 09:29 UTC by MahdiBM

The `DecodingError`'s description, when returned from HTTP requests, was missing some important info and sometimes was not clear enough. Hopefully this PR can resolve that issue.

2023-03-01 09:38 UTC, MahdiBM commented
I'll take care of the tests if the changes seem OK.

2023-03-01 10:02 UTC, 0xTim requested changes
Makes sense but would like to see some tests for the 3 different error paths

2023-03-01 13:40 UTC, MahdiBM commented on Tests/VaporTests/ContentTests.swift
> +            XCTAssertContains(
Had to use "Contains"  check instead of "Equal", because the errors could differ on macOS vs on Linux.

2023-03-01 13:40 UTC, MahdiBM commented on Sources/Vapor/Error/AbortError.swift
> +            return ""
didn't mention it in the documentation above the variable but i saw somewhere in JSONDecoder there was an empty `debugDescription` passed into the context.

2023-03-01 13:40 UTC, MahdiBM commented on Sources/Vapor/Error/AbortError.swift
>          case .dataCorrupted(let ctx):
I took a look at the JSONDecoder and Codable implementations and these descriptions are what i came up

2023-03-01 13:40 UTC, MahdiBM commented on Tests/VaporTests/ContentTests.swift
> +    func testDataCorruptionError() throws {
tests added for the 3 missing cases. 1 case already had a test (the one above)

2023-03-01 13:40 UTC, MahdiBM commented on Tests/VaporTests/ContentTests.swift
> +                #"Value required for key at path 'is_free'. No value associated with key CodingKeys(stringValue: "is_free", intValue: nil) ("is_free")."#
The explanation basically repeats itself twice. This is the case with Foundation's `JSONDecoder` errors but i thought maybe someone uses another decoder so better to keep the info

2023-03-01 13:51 UTC, MahdiBM commented
had to cancel 2 macos tests because it was taking 18+ minutes. unlikely to be related to this pr

2023-03-06 23:55 UTC, 0xTim approved these changes

2023-03-06 23:55 UTC, 0xTim commented
Thanks!

2023-03-07 00:19 UTC, merged