Add Sendable Conformances to undelying types
vapor/vapor pull request #3054
Opened 2023-08-10 16:57 UTC by 0xTim

This adds Sendable annotations to many of Vapor's types and APIs, including the request handlers.

APIs are marked `@proconcurrency` where it makes sense to reduce warnings for anyone using the release. To fix your code and see the warnings, you can enable strict concurrency checking.

**Note:** this PR does not touch `Request`, `Response` or `Application` as they require fundamental changes that are larger in scope and will be done in a future release.

2023-08-13 16:57 UTC, gwynne requested changes

2023-08-13 16:57 UTC, gwynne commented on Sources/Vapor/Error/StackTrace.swift
> +public struct StackTrace: Sendable {
I hate that we even have this code 😕

2023-08-13 16:57 UTC, gwynne commented on Sources/Vapor/Exports.swift
> +@_documentation(visibility: internal) @_exported import enum NIO.System
```suggestion
@_documentation(visibility: internal) @_exported import struct NIOCore.ByteBuffer
@_documentation(visibility: internal) @_exported import struct NIOCore.ByteBufferAllocator
@_documentation(visibility: internal) @_exported import protocol NIOCore.Channel
@_documentation(visibility: internal) @_exported import class NIOCore.EmbeddedChannel
@_documentation(visibility: internal) @_exported import class NIOCore.EmbeddedEventLoop
@_documentation(visibility: internal) @_exported import protocol NIOCore.EventLoop
@_documentation(visibility: internal) @_exported import class NIOCore.EventLoopFuture
@_documentation(visibility: internal) @_exported import protocol NIOCore.EventLoopGroup
@_documentation(visibility: internal) @_exported import struct NIOCore.EventLoopPromise
@_documentation(visibility: internal) @_exported import class NIOCore.MultiThreadedEventLoopGroup
@_documentation(visibility: internal) @_exported import struct NIOCore.NonBlockingFileIO
@_documentation(visibility: internal) @_exported import class NIOCore.NIOThreadPool
@_documentation(visibility: internal) @_exported import enum NIOCore.System
```
Plus editing the imports in the `#else` clause of course.

2023-08-13 16:57 UTC, gwynne commented on Sources/Vapor/Utilities/DotEnv.swift
> +            let fileHandleWrapper = NIOLoopBound(arg.0, eventLoop: eventLoop)
Okay, I've seen this pattern with file handles enough times now to be seriously bothered. This doesn't feel at all correct - `FileHandle` isn't `Sendable` because it implies sharing file descriptors across threads, which is a recipe for truly epic amounts of disaster. I don't have a better suggestion, but I'd love it if someone like Fabian or Cory could weigh in 😕

2023-08-13 16:57 UTC, gwynne commented on Sources/Vapor/Utilities/DotEnv.swift
>          return fileio.openFile(path: path, eventLoop: eventLoop).flatMap { arg -> EventLoopFuture<ByteBuffer> in
```suggestion
        return fileio.openFile(path: path, eventLoop: eventLoop).flatMapWithEventLoop { arg, eventLoop -> EventLoopFuture<ByteBuffer> in
```

2023-08-13 16:57 UTC, gwynne commented on Sources/Vapor/Utilities/OptionalType.swift
> +public func ??<T: Sendable>(lhs: EventLoopFuture<T?>, rhs: T) -> EventLoopFuture<T> {
It's extremely unfortunate that this is `public`...

2023-08-13 16:57 UTC, gwynne commented on Sources/Vapor/Utilities/RFC1123.swift
>          // parse components
No. This is wrong - you leave a nice wide gap where the components are out of sync with the timestamp. They need to both be under the same lock.

2023-08-13 17:39 UTC, 0xTim commented on Sources/Vapor/Utilities/DotEnv.swift
> +            let fileHandleWrapper = NIOLoopBound(arg.0, eventLoop: eventLoop)
This was the suggestion - file handle isn't Sendable but wrapping it with this at least makes it safe to use (and gets rid of the warnings)

2023-08-13 17:55 UTC, gwynne commented on Sources/Vapor/Utilities/DotEnv.swift
> +            let fileHandleWrapper = NIOLoopBound(arg.0, eventLoop: eventLoop)
Gets rid of the warnings, certainly. I'm not convinced it does a darn thing in terms of safety in either direction.

2023-08-14 23:56 UTC, 0xTim commented on Sources/Vapor/Utilities/OptionalType.swift
> +public func ??<T: Sendable>(lhs: EventLoopFuture<T?>, rhs: T) -> EventLoopFuture<T> {
On the plus side this should be pretty out of use with async/await

2023-08-14 23:58 UTC, 0xTim commented on Sources/Vapor/Utilities/DotEnv.swift
>          return fileio.openFile(path: path, eventLoop: eventLoop).flatMap { arg -> EventLoopFuture<ByteBuffer> in
What benefit does this give us over the current implementation given we're sticking to the same event loop?

2023-08-15 00:02 UTC, 0xTim commented on Sources/Vapor/Error/StackTrace.swift
> +public struct StackTrace: Sendable {
We can probably wrap this in a 5.9 flag when that's out as that provides proper runtime backtrace support in the language

2023-08-15 00:05 UTC, 0xTim commented on Sources/Vapor/Utilities/DotEnv.swift
> +            let fileHandleWrapper = NIOLoopBound(arg.0, eventLoop: eventLoop)
@fabianfett @FranzBusch any thoughts?

2023-08-15 00:12 UTC, 0xTim commented on Sources/Vapor/Content/ContentConfiguration.swift
> +        }
The compiler is having issues with this
```
'&' may only be used to pass an argument to inout parameter
Cannot find 'yield' in scope
```

2023-08-15 01:07 UTC, 0xTim commented on Sources/Development/routes.swift
> +    @Sendable
Essentially because it's required at the low level by NIO in `completeWithTask`, which means that the route builders are required to be `Sendable` so routes should be `Sendable` hence the annotation. The `@preconcurrency` annotation removes it for most users unless they have strict concurrency checking on

2023-08-15 01:18 UTC, 0xTim commented on Package.swift
> +}
We can only do this if we set the tools version to 5.9 for the whole package

2023-08-15 02:00 UTC, gwynne commented on Sources/Vapor/Utilities/DotEnv.swift
>          return fileio.openFile(path: path, eventLoop: eventLoop).flatMap { arg -> EventLoopFuture<ByteBuffer> in
Fewer captures is always a good thing - especially when you remember that `EventLoop` is actually `any EventLoop` (existentials suck).

2023-08-15 02:03 UTC, gwynne commented on Sources/Vapor/Content/ContentConfiguration.swift
> +        }
Ah, I'm guessing the special `_modify` syntax only works within the same scope... Try this:
```swift
_modify {
    self._globalLock.lock()
    defer { self._globalLock.unlock() }
    yield &self._global
}
```
(Obviously you'll have to use a plain `NIOLock` rather than a box for this)

2023-08-15 11:40 UTC, 0xTim commented on Package.swift
> +}
Ok separate manifests it is

2023-08-16 11:10 UTC, Lukasa commented on Sources/Vapor/Utilities/DotEnv.swift
> +            let fileHandleWrapper = NIOLoopBound(arg.0, eventLoop: eventLoop)
`NIOLoopBound` makes its `Sendable` contract work by runtime checks: if you create a `NIOLoopBound` from off the `eventLoop` you've bound it to, or use it from off that `eventLoop`, you'll get a runtime crash.

2023-08-16 11:44 UTC, gwynne commented on Sources/Vapor/Utilities/DotEnv.swift
> +            let fileHandleWrapper = NIOLoopBound(arg.0, eventLoop: eventLoop)
Nothing I didn't already know, but good enough just the same 🙂

2023-08-16 11:47 UTC, gwynne commented on Package@swift-5.7.swift
@0xTim The pattern I'm using in `MySQLNIO` is to keep `Package.swift` at tools-version 5.7 and have `Package@swift-5.8.swift` adding the use of `.enableUpcomingFeature()`. (I also have an additional `Package@swift-5.9.swift` to further reference the couple of macros I've tinkered with, but that'll probably go away before I PR the lot.) I'm not actually clear on whether it's more idiomatic to put the highest or the lowest version in the base manifest, though. Definitely wouldn't mind getting @neonichu's thoughts on that one.

2023-08-16 11:48 UTC, gwynne approved these changes
Tentatively approved, but FWIW I can't really claim to be happy with it yet.

2023-08-16 11:49 UTC, gwynne commented on Package@swift-5.9.swift
@0xTim The pattern I'm using in `MySQLNIO` is to keep `Package.swift` at tools-version 5.7 and have `Package@swift-5.8.swift` adding the use of `.enableUpcomingFeature()`. (I also have an additional `Package@swift-5.9.swift` to further reference the couple of macros I've tinkered with, but that'll probably go away before I PR the lot.) Basically, what you've done here. I'm not actually clear on whether it's more idiomatic to put the highest or the lowest version in the base manifest, though. Definitely wouldn't mind getting @neonichu's thoughts on that one.

2023-08-16 12:09 UTC, FranzBusch commented on Sources/Development/routes.swift
> +    @Sendable
Nothing here should ever use `@Sendable` on a method. This is highly unlikely to be the right thing ever. `@Sendable` on a method just disables all sendable checking at all. Rather the type itself needs to become `Sendable` here.

2023-08-16 12:09 UTC, FranzBusch commented on Sources/Vapor/Content/ContentConfiguration.swift
> +        }
Do we actually want people to be able to modify the global configuration here? Otherwise we could just trap on the `set` path and disallow this.

2023-08-16 12:25 UTC, gwynne commented on Sources/Vapor/Content/ContentConfiguration.swift
> +        }
Unfortunately, yes, Vapor is stuck with this very broken API pattern where modifying the global configuration is the "correct" behavior. Yet another fun consequence of Tanner's designs and semver rules.

2023-08-16 12:26 UTC, gwynne commented on Sources/Development/routes.swift
> +    @Sendable
Thank you, I knew this felt wrong 😰

2023-08-16 12:27 UTC, gwynne commented on Package.swift
> +}
Since you've done that, please remove the changes to the original manifest and the test workflow

2023-08-16 13:49 UTC, 0xTim commented on Package@swift-5.9.swift
Yeah I switched to that. Having the highest version in the base manifest seemed to break various CI tests, which seems like a SwiftPM bug but I didn't have a chance to investigate

2023-08-16 13:59 UTC, 0xTim commented on Sources/Development/routes.swift
> +    @Sendable
@FranzBusch hmm even making `Request` `@unchecked Sendable` just to try it out results in
```swift
Converting non-sendable function value to '@Sendable (Request) async throws -> String' may introduce data races
```
any idea?

2023-08-16 14:10 UTC, FranzBusch commented on Sources/Development/routes.swift
> +    @Sendable
You have to keep in mind that `self` is also a parameter for this method so you gotta make sure that `Self` is also `Sendable` in this case probably `Creds`

2023-08-16 14:18 UTC, 0xTim commented on Sources/Development/routes.swift
> +    @Sendable
`Self` here is top level code, it's a function not in any type. Is that going to cause issues?

2023-08-16 14:20 UTC, 0xTim commented on Sources/Development/routes.swift
> +    @Sendable
Just tried putting the routes in a type that's `Sendable` and no changes

2023-08-16 14:21 UTC, gwynne commented on Sources/Vapor/Content/ContentConfiguration.swift
> +        }
The compiler doesn't synthesize the efficient version, considering the lock, but in retrospect that's a silly consideration for `ContentConfiguration` anyway, I withdraw this particular suggestion 😅

2023-08-16 14:26 UTC, FranzBusch commented on Sources/Development/routes.swift
> +    @Sendable
Ah wait sorry I was mis reading the surrounding context in the diff. Yeah this is a known compiler deficiency. I recommend changing these local methods to be local closures. You can then write them like this

```
let asyncRouteTester: @Sendable (Request) async throws -> String = {
}
```

This will make the compiler properly check the closure for `@Sendable` and also solve the original warning that you got.

2023-08-16 14:29 UTC, 0xTim commented on Sources/Development/routes.swift
> +    @Sendable
@FranzBusch Is there a bug on GH for this or plans to solve this? To give you some context this file is just for trying out Vapor's APIs so rewriting the functions to closures here is fine but then we'd be telling everyone that every single route handler would need to be changed from a function to a closure

2023-08-16 14:30 UTC, 0xTim commented on Sources/Development/routes.swift
> +    @Sendable
PS it's not a major issue at the moment as the APIs are marked with `@preconcurrency` so you only get the warnings if you manually turn on strict concurrency checking

2023-08-16 14:32 UTC, FranzBusch commented on Sources/Development/routes.swift
> +    @Sendable
It is not about people getting warnings when using `@Sendable` on a method but rather that the compiler is not checking your code if it really is `Sendable`. There is a pitch and some discussion around this topic here: https://forums.swift.org/t/pitch-inferring-sendable-for-methods/66565

2023-08-18 15:19 UTC, gwynne requested changes
One last nit

2023-08-18 15:19 UTC, gwynne commented on .github/workflows/test.yml
> +
This is useless; we already run against the latest 5.9 nightly in the reusable workflow.

2023-08-18 15:20 UTC, 0xTim commented on .github/workflows/test.yml
> +
That's a good point actually. The check doesn't really do much yet anyway since we don't have warnings as errors turned on (and I'm doubtful if we ever will be able to with strict concurrency checking in Vapor 4)

2023-08-18 15:22 UTC, gwynne approved these changes

2023-08-18 15:37 UTC, merged