Make Response Sendable
vapor/vapor pull request #3055
Opened 2023-08-10 23:43 UTC by 0xTim

Makes `Response` `Sendable`

2023-08-11 00:08 UTC, 0xTim commented
This should be merged after #3054

2023-08-13 17:05 UTC, gwynne requested changes
There's probably more, this is just off the top of my head

2023-08-13 17:05 UTC, gwynne commented on Sources/Vapor/HTTP/BodyStream.swift
> +        }
Ditto on "Trash all this; I have a fully rewritten state-machine-based properly Sendable version locally that I'll PR shortly" 😅

2023-08-13 17:05 UTC, gwynne commented on Sources/Vapor/Response/Response.swift
> +    }
It's not _technically_ necessary, but for cleanliness' sake, can we put these three under a single lock, given how closely related to each other they are?

2023-08-13 17:05 UTC, gwynne commented on Sources/Vapor/Response/Response.swift
> +        }
Not correct unless you take the headers lock as well during both get and set (that's "take the headers lock _AND_ the body lock" not "take them in sequence")

2023-11-01 18:39 UTC, 0xTim commented
Implemented in #3082

2023-11-01 18:39 UTC, closed without merging