Make Storage Sendable
vapor/vapor pull request #3056
Opened 2023-08-19 13:44 UTC by 0xTim

Make Vapor's `Storage` `Sendable`. This is a key piece in allowing `Request`, `Response` and `Application` to be `Sendable`.

Note that types that are stored in `Storage` should now be `Sendable`. If you get any warnings, you may need to update your code for this new change.

2023-08-19 16:00 UTC, 0xTim commented
Need to be careful here on how the Sendable stuff changes things like Authentication in Fluent

2023-08-23 14:50 UTC, 0xTim commented
@gwynne @franzbusch @fabianfett this is ready for review if anyone would like to take a look

2023-08-24 10:45 UTC, gwynne requested changes

2023-08-24 10:45 UTC, gwynne commented on Sources/Vapor/Application.swift
> +            }
This will not work as intended. I assume I don't have to explain why 😅

2023-08-24 10:45 UTC, gwynne commented on Sources/Vapor/HTTP/EndpointCache.swift
> +                    }
If you have to nest locks like this, that's a sign that both items should be guarded by the same lock. In general I think you're making your locks too fine-grained because `NIOLockedValueBox` makes it so easy. An actor's properties are all guarded by the same task, for example.

2023-08-24 10:45 UTC, gwynne commented on Sources/Vapor/HTTP/Server/HTTPServer.swift
> +#warning("We were storing a weak reference to the applicaiton at this point - why")
Because otherwise you'd have a retain cycle between the application and the channel handlers.

2023-08-24 11:18 UTC, 0xTim commented on Sources/Vapor/Application.swift
> +            }
🤦

2023-08-24 11:18 UTC, 0xTim commented on Sources/Vapor/HTTP/EndpointCache.swift
> +                    }
Tuples for the win!

2023-08-24 11:22 UTC, 0xTim commented on Sources/Vapor/HTTP/Server/HTTPServer.swift
> +#warning("We were storing a weak reference to the applicaiton at this point - why")
I'm not overtly happy with having a crash point here but I don't think there's any other way to recover

2023-08-24 11:27 UTC, gwynne approved these changes

2023-08-28 14:07 UTC, merged