More Sendable Conformances
vapor/vapor pull request #3057
Opened 2023-08-30 02:00 UTC by 0xTim

This adds more Sendable conformances to Vapor and resolves any Sendable warnings that aren't related to `Request` or `Response`

2023-08-31 12:44 UTC, 0xTim commented
@fabianfett @franzbusch if you'd like to have a look that would be great! This has more changes than simply wrapping properties in `NIOLockedValueBox` as it touches parts of NIO that can't be `Sendable`

2023-08-31 15:35 UTC, fabianfett commented on Sources/Vapor/HTTP/Server/HTTPServerResponseEncoder.swift
> +    let isComplete: NIOLockedValueBox<Bool>
why not use ManagedAtomics here?

2023-08-31 15:37 UTC, fabianfett commented on Sources/Vapor/HTTP/Server/HTTPServerResponseEncoder.swift
>      }
trick17: pass `the eventLoop` in the init and then store it as a let

2023-08-31 15:38 UTC, fabianfett commented on Sources/Vapor/HTTP/Server/HTTPServerResponseEncoder.swift
> +                    promise?.fail(Error.notEnoughBytes)
same as above.

2023-08-31 15:41 UTC, fabianfett commented on Sources/Vapor/HTTP/Server/HTTPServerResponseEncoder.swift
> +    let isComplete: NIOLockedValueBox<Bool>
are those only changed on EL? If that's the case, why do they need a Lock?

2023-08-31 15:41 UTC, fabianfett commented on Sources/Vapor/Response/Response+Body.swift
> +    let promise: NIOLockedValueBox<EventLoopPromise<ByteBuffer>>
Why do you need locks here? Those are `let`s...

2023-08-31 15:44 UTC, 0xTim commented on Sources/Vapor/Response/Response+Body.swift
> +    let promise: NIOLockedValueBox<EventLoopPromise<ByteBuffer>>
They weren't before the were wrapped in `NIOLockedValueBox` - we mutate them inside the class, hence the need for a lock

2023-08-31 15:45 UTC, 0xTim commented on Sources/Vapor/Response/Response+Body.swift
> +    }
Yeah I don't know why this was mutable to start with in hindsight, it doesn't look like we mutate it anywhere

2023-08-31 15:46 UTC, 0xTim commented on Sources/Vapor/HTTP/Server/HTTPServerResponseEncoder.swift
> +    let isComplete: NIOLockedValueBox<Bool>
Inside the stream, they should only be changed on the event loop. We could use `LoopBound` 👍

2023-08-31 15:51 UTC, 0xTim commented on Sources/Vapor/HTTP/Server/HTTPServerResponseEncoder.swift
> +    let isComplete: NIOLockedValueBox<Bool>
I hadn't actually considered ManagedAtomics

2023-08-31 16:18 UTC, 0xTim commented on Sources/Vapor/HTTP/Server/HTTPServerResponseEncoder.swift
> +                    promise?.fail(Error.notEnoughBytes)
No longer an issue if we moved to managed atomics

2023-08-31 16:22 UTC, 0xTim commented on Tests/VaporTests/ApplicationTests.swift
> +            let shutdownFlag: NIOLockedValueBox<Bool>
Nice idea 👍

2023-09-05 09:33 UTC, fabianfett commented on Sources/Vapor/HTTP/Server/HTTPServerHandler.swift
> +            box.value.1.serialize(response, for: request, context: box.value.0)
this is likely still two checks? Why not just get the value once and then do the split after that?

2023-09-05 09:44 UTC, fabianfett commented on Tests/VaporTests/ApplicationTests.swift
> +            let shutdownFlag: NIOLockedValueBox<Bool>
will you fix it?

2023-09-05 13:29 UTC, 0xTim commented on Tests/VaporTests/ApplicationTests.swift
> +            let shutdownFlag: NIOLockedValueBox<Bool>
Ah missed this. No I decided against this because we check the state for the 3 different properties independently (e.g. when `didBoot` is called, `willBoot` should also have been called. The state machine for lifecycle stuff doesn't have a way to distinguish this without an enum with lots of different values. Since it's just tests I stuck it with 3 locks

2023-09-06 09:41 UTC, gwynne requested changes
Definitely shaping up, but several additional nits.

2023-09-06 09:41 UTC, gwynne commented on Sources/Vapor/HTTP/Server/HTTPServerResponseEncoder.swift
> +            self.isComplete.store(true, ordering: .relaxed)
Why relaxed ordering on this but not elsewhere?

2023-09-06 09:41 UTC, gwynne commented on Sources/Vapor/Request/Request+BodyStream.swift
> +        private let handlerBuffer: NIOLoopBoundBox<HandlerBufferContainer>
The properties are either loop-bound or they're locked, why would they be both?

2023-09-06 09:41 UTC, gwynne commented on Sources/Vapor/Response/Response+Body.swift
> +    let buffer: NIOLockedValueBox<ByteBuffer>
This can and should be loop-bound instead of locked; see also below...

2023-09-06 09:41 UTC, gwynne commented on Sources/Vapor/HTTP/Server/HTTPServerResponseEncoder.swift
> +            if let count = self.count, self.currentCount.load(ordering: .sequentiallyConsistent) > count {
Why not `self.currentCount.wrappingIncrementThenLoad(by: buffer.readableBytes, ordering: .sequentiallyConsistent)`?

2023-09-06 09:41 UTC, gwynne commented on Sources/Vapor/HTTP/Server/HTTPServerResponseEncoder.swift
> +            if let count = self.count, self.currentCount.load(ordering: .sequentiallyConsistent) != count {
```suggestion
            if let count = self.count, self.currentCount.load(ordering: .sequentiallyConsistent) < count {
```
Preexisting semantic bug - "too many bytes" is not the same as "not enough bytes".

2023-09-06 09:41 UTC, gwynne commented on Sources/Vapor/Response/Response+Body.swift
>      }
Borrowed slightly from my much more heavily revised version:
```swift
    func write(_ result: BodyStreamResult, promise: EventLoopPromise<Void>?) {
        let future = self.eventLoop.submit {
            switch result {
            case .buffer(var buffer):
                self.buffer.writeBuffer(&buffer)
            case .error(let error):
                self.promise.fail(error)
                throw error
            case .end:
                self.promise.succeed(self.buffer)
            }
        }
        // N.B.: Preexisting semantic bug: Errors in the stream should fail the individual write promise.
        if let promise { future.cascade(to: promise) }
    }
```

2023-09-06 09:43 UTC, 0xTim commented on Sources/Vapor/HTTP/Server/HTTPServerResponseEncoder.swift
> +            self.isComplete.store(true, ordering: .relaxed)
Because I wasn't reading it elsewhere, I'll switch to sequential

2023-09-06 09:44 UTC, 0xTim commented on Sources/Vapor/Request/Request+BodyStream.swift
> +        private let handlerBuffer: NIOLoopBoundBox<HandlerBufferContainer>
Sendable types are protected by locks, anything that isn't sendable needs to go in a `LoopBoundBox`. I haven't got a clear answer on which is the most performant

2023-09-06 09:45 UTC, 0xTim commented on Sources/Vapor/Response/Response+Body.swift
> +    let buffer: NIOLockedValueBox<ByteBuffer>
It can't be unfortunately. There are instances where the `BodyStreamWriter` is created off an event loop. If we tried to use `LoopBound` at this point, we'd fail the preconditions

2023-09-06 09:46 UTC, 0xTim commented on Sources/Vapor/HTTP/Server/HTTPServerResponseEncoder.swift
> +            if let count = self.count, self.currentCount.load(ordering: .sequentiallyConsistent) > count {
I didn't know the API existed 😅

2023-09-06 09:47 UTC, 0xTim commented on Sources/Vapor/HTTP/Server/HTTPServerResponseEncoder.swift
> +            if let count = self.count, self.currentCount.load(ordering: .sequentiallyConsistent) != count {
Ok I need to dig into this, because we should probably have a test for it

2023-09-06 09:52 UTC, 0xTim commented on Sources/Vapor/Response/Response+Body.swift
>      }
Do you have a corresponding test I could pull in for this?

2023-09-06 09:58 UTC, gwynne commented on Sources/Vapor/Response/Response+Body.swift
>      }
I wish; I never got that far, unfortunately 😕.

2023-09-06 10:00 UTC, gwynne commented on Sources/Vapor/Response/Response+Body.swift
> +    let buffer: NIOLockedValueBox<ByteBuffer>
You can work around that with `NIOLoopBoundBox.makeEmptyBox()`

2023-09-06 10:10 UTC, gwynne commented on Sources/Vapor/Request/Request+BodyStream.swift
> +        private let handlerBuffer: NIOLoopBoundBox<HandlerBufferContainer>
- `NIOLockedValueBox` is as performant as the allocation plus a standard `pthread_mutex_t`. 
- `NIOLoopBound[Box]` is as performant as the cost of `EventLoop.inEventLoop`, which given a `MTELG` with Glibc is `pthread_equal()` + `pthread_self()`, where `pthread_equal()` is a single `==` and `pthread_self()` is a simple register load on both amd64 and arm64), plus the cost of allocation if using the box.

Given that a `pthread_mutex_t` can cost anywhere from a single atomic-CAS operation to an arbitrarily long wait time, I'd say it's a safe bet the loop-bound is less expensive.

2023-09-06 14:13 UTC, 0xTim commented on Sources/Vapor/Response/Response+Body.swift
> +    let buffer: NIOLockedValueBox<ByteBuffer>
Will fix this is a future PR

2023-09-09 16:10 UTC, gwynne commented on Sources/Vapor/Response/Response+Body.swift
> +        let future = self.eventLoop.submit {
Since the execution of this logic is now event loop-bound, does the buffer still need to be locked?

2023-09-21 13:21 UTC, 0xTim commented on Sources/Vapor/Response/Response+Body.swift
> +        let future = self.eventLoop.submit {
Technically no, we can make this unchecked

2023-09-22 06:54 UTC, gwynne requested changes
A couple bits and pieces, and one "hey if this is correct (and you should make sure I'm right before doing anything about it) it blows the whole PR out of the water" concern 😅

2023-09-22 06:54 UTC, gwynne commented on Package.swift
> +        .package(url: "https://github.com/apple/swift-atomics.git", from: "1.1.0"),
Add to `Package@swift-5.9.swift` also.

2023-09-22 06:54 UTC, gwynne commented on Package.swift
> +            .product(name: "Atomics", package: "swift-atomics"),
Add to `Package@swift-5.9.swift`

2023-09-22 06:54 UTC, gwynne commented on Sources/Vapor/Utilities/FileIO.swift
> +        onRead: @Sendable @escaping (ByteBuffer) -> EventLoopFuture<Void>
Am I completely off my rocker, or wouldn't it be valid to just _NOT_ make this `@Sendable`? Per SE-0302, `@Sendable` means "this function type is safe to pass across concurrency domains" - except this is the ELF-based API, which means there are no concurrency domains to cross here. And if the closure isn't sendable, we no longer have to waste a bunch of time acquiring and releasing a lock over and over for the buffer in `collectFile()`.

(And, obviously, if my understanding here is correct then the same "let's only use the attribute when it's accurate to use it" logic should be applied to the entire PR. Too bad we can't remove it from anywhere that already has it in released code, though...)

2023-09-22 06:54 UTC, gwynne commented on Tests/VaporTests/Utilities/CapturingMetricsSystem.swift
> +internal class TestRecorder: RecorderHandler, Equatable, @unchecked Sendable {
If we're gonna made `TestTimer` `final` (per below) then do it for this too.

2023-09-22 06:54 UTC, gwynne commented on Tests/VaporTests/Utilities/CapturingMetricsSystem.swift
> +internal class TestCounter: CounterHandler, Equatable, @unchecked Sendable {
If we're gonna made `TestTimer` `final` (per below) then do it for this too.

2023-09-22 15:04 UTC, 0xTim commented on Sources/Vapor/Utilities/FileIO.swift
> +        onRead: @Sendable @escaping (ByteBuffer) -> EventLoopFuture<Void>
> which means there are no concurrency domains to cross here

I think this isn't entirely correct. The caller of the function could create the function in one domain (such as an async route handler) that's then passed to another concurrency domain when we jump on to the event loop to actually call it so I think it is required.

(The eventual callsite of this where we pass the function is also marked as Sendable - https://github.com/apple/swift-nio/blob/main/Sources/NIOPosix/NonBlockingFileIO.swift#L82 - which also required the closure passed in to be Sendable I believe)

2023-09-25 01:14 UTC, gwynne approved these changes
I can't claim I find this PR to be a masterpiece of elegance and precision, but preconcurrency is preconcurrency, and as far as I can tell there aren't any actual _issues_ left.

2023-09-26 12:07 UTC, merged