Update Logger+Report.swift
vapor/vapor pull request #3068
Opened 2023-09-19 14:44 UTC by MahdiBM

2023-09-19 16:09 UTC, gwynne requested changes

2023-09-19 16:09 UTC, gwynne commented on Sources/Vapor/Logging/Logger+Report.swift
> +            reason = localized.errorDescription ?? "\(localized)"
I would prefer that we just remove the `as LocalizedError` case altogether and let it fall through to the default. Arguably we should do the same for `EncodingError` and `DecodingError` as well, since we don't do anything special for those errors (not anymore, anyway; we did a long time ago, before they had built-in descriptions of their own). This also leaves us no longer adding "special" handling for any error types except our own custom ones, which is in keeping with (if not strictly a case of obedience to) the general rule to only extend other frameworks' types with one's own protocols).

Honestly, the entire thing is a bit ridiculous in modern Swift (though it made sense in the 4.2 days). No one, in my experience, actually uses `DebuggableError` (certainly Vapor itself doesn't), nor `AbortError` for that matter (aside from the obvious sole purview of `Abort` itself).

2023-09-19 16:11 UTC, MahdiBM commented on Sources/Vapor/Logging/Logger+Report.swift
> +            reason = localized.errorDescription ?? "\(localized)"
I agree honestly, that was one other way I could have gone with the PR.

2023-09-19 16:18 UTC, MahdiBM commented on Sources/Vapor/Logging/Logger+Report.swift
> +            reason = localized.errorDescription ?? "\(localized)"
The `String(reflecting:)` is still useful though, specially with PostgresNIO and the upcoming other SQL driver changes.

2023-09-19 16:18 UTC, gwynne commented on Sources/Vapor/Logging/Logger+Report.swift
> +
Believe it or not, I actually approve of this whitespace change on cleanliness grounds 😆

2023-09-19 16:18 UTC, gwynne commented on Sources/Vapor/Logging/Logger+Report.swift
> +            reason = localized.errorDescription ?? "\(localized)"
Precisely so!

2023-09-19 16:20 UTC, MahdiBM commented on Sources/Vapor/Logging/Logger+Report.swift
> +
That's just my workspace settings doing that 😅
Xcode does have a settings for enabling that although this was vscode doing this.

2023-09-19 16:31 UTC, MahdiBM commented
Updated description of the PR since Penny uses that in the Release.

2023-09-20 16:26 UTC, gwynne approved these changes

2023-09-20 16:26 UTC, merged

2023-09-20 20:07 UTC, Gerzer commented
This change is a regression that should be reverted. See [my comment](https://github.com/apple/swift/issues/68102#issuecomment-1728355333) on the `apple/swift` issue.