Pass X-Request-Id if present
vapor/vapor pull request #3072
Opened 2023-09-21 22:07 UTC by paunik

Pass the value from the X-Request-Id to the logger context

- pass the X-Request-Id header value if present, pass generated UUID if the header not present

Why:
 - We needed a way to trace router -> web -> worker on the logger on the heroku and we found this https://devcenter.heroku.com/articles/http-request-id

Inspiration:
- https://api.rubyonrails.org/classes/ActionDispatch/RequestId.html
- https://http.dev/x-request-id

2023-09-21 22:11 UTC, gwynne requested changes
This looks fine, aside from the conflict markers left unresolved.

2023-09-21 22:11 UTC, gwynne commented on Sources/Vapor/Request/Request.swift
>          self.byteBufferAllocator = byteBufferAllocator
Please fixup this leftover merge conflict.

2023-09-21 22:14 UTC, paunik commented on Sources/Vapor/Request/Request.swift
>          self.byteBufferAllocator = byteBufferAllocator
on it

2023-09-21 22:16 UTC, paunik commented on Sources/Vapor/Request/Request.swift
>          self.byteBufferAllocator = byteBufferAllocator
Should be done, tnx for the quick check, I should have seen this myself.

2023-09-21 22:25 UTC, gwynne commented on Tests/VaporTests/HTTPHeaderTests.swift
> +
Can you also add an end-to-end test which checks that the header is used when present in a request?

2023-09-22 02:32 UTC, gwynne approved these changes

2023-09-22 05:47 UTC, dannflor approved these changes
Beautamous

2023-09-22 06:16 UTC, merged

2023-09-22 06:17 UTC, MahdiBM reviewed
Honestly considering this header doesn't make an appearance in MDN, I wouldn't hard-code it like this 🤔

I would instead add a configuration option so other users can configure it "based on headers", and there they could specify the "X-Request-ID" header.

I know this complicates the solution, but we have "tracing" and "task-locals" for logging now which enable you to this yourself to some extent, and caring about this particular header seems out of scope for Vapor to me.

2023-09-22 06:38 UTC, gwynne commented
@MahdiBM I disagree - `X-Request-ID` is not an official standard, true, but it is a de facto one. (Enough so, even for people to have gone to the trouble of noting that [RFC 6648](https://www.rfc-editor.org/rfc/rfc6648) deprecated the `X-` prefix on headers and remarked on the need to find a new name.) Unless you can cite links to any alternate names commonly used for the same purpose, configurability would just bloat the API surface and force users to do additional work without adding any real value.