bug: fix redirection with query parameters.
vapor/vapor pull request #3077
Opened 2023-10-01 17:08 UTC by Captain-Kirkie

Adding query parameters to file middle ware redirect. 

1) pulling query parameters from request url. 
2) re-appending them on redirect

Adding query parameters to file middle ware redirect.

2023-10-01 17:09 UTC, Captain-Kirkie commented
Issue [Here](https://github.com/vapor/vapor/issues/3076)

2023-10-05 22:42 UTC, 0xTim requested changes
Thanks for the PR! One change then we can merge

2023-10-05 22:42 UTC, 0xTim commented on Sources/Vapor/Middleware/FileMiddleware.swift
> +    public func getQueryString() -> String {
You can just use `req.url.query` instead

2023-10-05 23:05 UTC, gwynne commented on Sources/Vapor/Middleware/FileMiddleware.swift
> +                        request.redirect(to: request.url.path + "/" + queryStr, redirectType: .permanent)
Why not redirect the entire URL (with the modified path) so as to also preserve authority parameters (username, password) and other components such as the fragment (text following a `#`)?

2023-10-05 23:43 UTC, 0xTim commented on Sources/Vapor/Middleware/FileMiddleware.swift
> +                        request.redirect(to: request.url.path + "/" + queryStr, redirectType: .permanent)
That's a better solution

Not that fragment would be passed back to the server but the auth stuff would be

2023-10-07 02:37 UTC, Captain-Kirkie commented on Sources/Vapor/Middleware/FileMiddleware.swift
> +                        request.redirect(to: request.url.path + "/" + queryStr, redirectType: .permanent)
That is more elegant. I have updated the PR to use the entire URL.

2023-10-07 02:45 UTC, gwynne requested changes

2023-10-07 02:45 UTC, gwynne commented on Sources/Vapor/Middleware/FileMiddleware.swift
> +                        request.redirect(to: redirectLocation, redirectType: .permanent)
This is unsafe if the path occurs multiple times in the URL (which is perfectly possible). Try something like this, maybe:
```suggestion
                    var redirectUrl = request.url
                    redirectUrl.path += "/"
                    return request.eventLoop.future(request.redirect(to: redirectUrl.string, redirectType: .permanent))
```

2023-10-07 02:57 UTC, Captain-Kirkie commented on Sources/Vapor/Middleware/FileMiddleware.swift
> +                        request.redirect(to: redirectLocation, redirectType: .permanent)
whoops, good catch. Updated.

2023-10-11 12:18 UTC, 0xTim approved these changes
Thanks!

2023-10-11 12:31 UTC, merged