Make Request Sendable
vapor/vapor pull request #3093
Opened 2023-11-01 17:20 UTC by 0xTim

Final stage of Vapor's `Sendable` journey as `Request` is now `Sendable`. 

There should be no more `Sendable` warnings in Vapor, even with complete concurrency checking turned on.

2023-11-01 18:37 UTC, 0xTim commented
This was surprisingly easy in the end. Tried to reduce the locks where possible, I've added individual locks to where it's likely to be accessed concurrently

2023-11-04 06:12 UTC, MahdiBM requested changes
Looks good but some requested changes.

I also see one probably-resolvable warning in "Development" on 5.9:

> /__w/vapor/vapor/Sources/Development/routes.swift:274:36: warning: converting non-sendable function value to '@Sendable (Request) async throws -> some AsyncResponseEncodable' may introduce data races
    asyncRoutes.get("opaque", use: opaqueRouteTester)

2023-11-04 06:12 UTC, MahdiBM commented on Sources/Vapor/Routing/Route.swift
> +    }
This breaks API?
`[AnyHashable: Any]` -> `[AnySendableHashable: Sendable]`

2023-11-04 12:24 UTC, gwynne commented on .devcontainer/devcontainer.json
> +            ]
I tend to agree; this is an excessive addition unless we want to commit to keeping it maintained at least as much so as the rest of the support files we provide.

2023-11-04 12:25 UTC, gwynne commented on .gitignore
> +.cache/
Why would these be in the Vapor repo? Does VSCode end up using the package root as a user's homedir in dev containers? 🤨

2023-11-04 12:26 UTC, gwynne commented on Sources/Vapor/Commands/ServeCommand.swift
> +@preconcurrency import Foundation
Good catch, Mahdi 👍

2023-11-04 12:26 UTC, gwynne commented on Sources/Vapor/Commands/ServeCommand.swift
> +    private let server: NIOLockedValueBox<Server?>
Too-granular locking again, Tim.

2023-11-04 12:27 UTC, gwynne commented on Sources/Vapor/HTTP/Headers/HTTPCookies.swift
>          return self.cookies.map { $0.value.serialize(name: $0.key) }
I would much rather add it where it's missing than remove it where it exists. Lack of that setting was the very first thing I noticed as a problem with `swift-format`, even before its newlines problem

2023-11-04 12:27 UTC, gwynne commented on Sources/Vapor/HTTP/Headers/HTTPCookies.swift
> +        get { return self.cookies[name] }
Fix the statements around it.

2023-11-04 12:28 UTC, gwynne commented on Sources/Vapor/Routing/Route.swift
> +    }
Correct, it does.

2023-11-04 12:30 UTC, gwynne commented on Sources/Vapor/Routing/Route.swift
I would hasten to point out that there's nothing held by `Route` that inherently makes it non-`Sendable` in theory- or for that matter, that justifies it being a reference type rather than a value type in the first place (or for _that_ matter, that justifies it being mutable at _all_!). I know that can't be changed without breaking API, but it does suggest that `@unchecked Sendable` ("I know what I'm doing, punish me if I hork it up") might be a better choice than a bunch of locking no one should be hitting to begin with.

2023-11-04 12:35 UTC, gwynne commented on Sources/Vapor/Utilities/AnySendableHashable.swift
> +    public init(_ wrappedValue: any Hashable & Sendable) {
```suggestion
    public init(_ wrappedValue: some Hashable & Sendable) {
```
This brings it in line with `AnyHashable`'s initializer:
```swift
@frozen public struct AnyHashable {
    public init<H>(_ base: H) where H : Hashable
```
(which is functionally identical to `public init(_ base: some Hashable)`)

2023-11-04 12:38 UTC, gwynne commented on Sources/Vapor/Utilities/AnySendableHashable.swift
> +}
`AnyHashable` isn't `ExpressibleByStringLiteral`, where did that come from?

Also, to be equivalent to `AnyHashable`, you need to add:
```swift
extension AnySendableHashable: CustomStringConvertible, CustomDebugStringConvertible, CustomReflectable {
    public var description: String { self.wrappedValue.description }
    public var debugDescription: String { self.wrappedValue.debugDescription }
    public var customMirror: Mirror { self.wrappedValue.customMirror }
}

2023-11-04 12:38 UTC, gwynne requested changes
Per comments above

2023-11-04 13:06 UTC, MahdiBM commented on Sources/Vapor/Routing/Route.swift
> +    }
What do we want to do then? Live with it and just make it as least noticeable as possible?

2023-11-04 15:25 UTC, 0xTim commented on .gitignore
> +.cache/
This was from me running a quick interactive Docker container to test on Linux - I didn't think it was an issue to add them

2023-11-04 15:28 UTC, 0xTim commented on Sources/Vapor/Utilities/AnySendableHashable.swift
> +}
This was a direct lift from [ConsoleKit](https://github.com/vapor/console-kit/blob/21b72c579a0d04a530e2b2f456c551c5b8940cf8/Sources/ConsoleKit/Terminal/Terminal.swift#L12) - we should probably do the same there

2023-11-04 15:30 UTC, gwynne commented on Sources/Vapor/Utilities/AnySendableHashable.swift
> +}
Then why in the world are you copying it into Vapor? You've already got ConsoleKit's version available, it's public.

2023-11-04 15:30 UTC, 0xTim commented on Sources/Vapor/Routing/Route.swift
> +    }
It _should_ only introduce warnings for people (unless they're relying on specific signatures). We did the same in ConsoleKit so the precedent has been set there

2023-11-04 15:36 UTC, 0xTim commented on Sources/Vapor/Utilities/AnySendableHashable.swift
> +}
Err that I don't have a good answer for!

2023-11-04 15:37 UTC, 0xTim commented on Sources/Vapor/Commands/ServeCommand.swift
> +@preconcurrency import Foundation
`DispatchSourceSignal` isn't `Sendable` on either platform so it's required here for now

2023-11-04 15:39 UTC, 0xTim commented on Sources/Vapor/Routing/Route.swift
The only thing that requires this here is `PathComponent` which we can make Sendable and I'll do in another PR when I tackle RoutingKit. That one I want to be very careful with though for obvious reasons

2023-11-04 15:42 UTC, 0xTim commented on Sources/Vapor/Routing/Route.swift
Wrt to the whole thing of `Route` and unchecked `Sendable` I'm planning on doing a better audit of Vapor things, deprecating thing and then introducing a new `AsyncRoute` in it's place

2023-11-04 16:41 UTC, 0xTim commented on Sources/Vapor/Commands/ServeCommand.swift
> +    private let server: NIOLockedValueBox<Server?>
I did this because it's in the top level command so shouldn't affect things (since it's only used at app start up) but will change

2023-11-04 16:42 UTC, 0xTim commented
@MahdiBM that's an annoying Swift bug with complete concurrency checking and nothing we can do at the moment until it's fixed in Swift

2023-11-04 16:45 UTC, MahdiBM commented
O it's that bug... you can just open up the closure and the bug will go away. Though I'm fine with it either way since it's a bug.

2023-11-04 16:49 UTC, MahdiBM approved these changes

2023-11-04 18:42 UTC, gwynne approved these changes

2023-11-06 11:37 UTC, merged