Use `singleton` `EventLoopGroup`
vapor/vapor pull request #3128
Opened 2024-01-03 19:31 UTC by MahdiBM

2024-01-03 19:32 UTC, MahdiBM commented on Package.swift
> +        .package(url: "https://github.com/vapor/routing-kit.git", from: "4.8.2"),
Some Sendable warnings are fixed in this version.

2024-01-03 19:33 UTC, MahdiBM commented on Sources/Vapor/Application.swift
>          case createNew
Deprecate this.

2024-01-03 19:33 UTC, MahdiBM commented on Tests/VaporTests/ServerTests.swift
> +        let app = Application(.testing, .createNew)
Use `createNew` just so there is something testing it.

2024-01-07 12:07 UTC, dimitribouniol commented on Sources/Vapor/Application.swift
> +        _ eventLoopGroupProvider: EventLoopGroupProvider = .shared(NIOSingletons.posixEventLoopGroup)
Since you declared a `.singleton`, shouldn't this use it so there's less to refactor if the default should be a different singleton in the future?
```suggestion
        _ eventLoopGroupProvider: EventLoopGroupProvider = .singleton
```

2024-01-07 14:35 UTC, gwynne commented on Sources/Vapor/Application.swift
> +            .shared(NIOSingletons.posixEventLoopGroup)
Use `MultiThreadedEventLoopGroup.singleton` instead.

2024-01-07 14:35 UTC, gwynne requested changes
See comment.

2024-01-07 16:31 UTC, gwynne approved these changes

2024-01-07 16:31 UTC, gwynne commented
You can ignore the macOS test failure.

2024-01-07 17:00 UTC, dimitribouniol approved these changes
Looking forward to using this immediately, thanks!

2024-01-07 17:05 UTC, merged