Updated HTTPServer's configuration to be dynamically updatable
vapor/vapor pull request #3132
Opened 2024-01-07 21:40 UTC by dimitribouniol

This allows many aspects of the HTTP server configuration to be changed after the server starts without needing to stop and restart it, or drop existing connections in the process.

Some things that can now be re-configured include request/response configuration options, HTTP version support, HTTP pipelining, TLS configuration (ie. enabling/disabling, rotating certificates, etc…), server name, metrics reporting, the logger, and the shutdown timer.

Fixes #3130.

2024-01-17 14:28 UTC, dimitribouniol commented
Gentle poke to see if there's anything I can help with to get this over the finish line 😊

2024-02-11 13:58 UTC, dimitribouniol commented
Just wanted to check in again to see if there's anything holding this from being merged in — if it's a migration to async channels, I can dedicate some time to making that happen as I'm highly motivated to no longer rely on a private fork of vapor for my production deploy 😅

2024-02-14 13:33 UTC, 0xTim requested changes
@dimitribouniol sorry for the delay! I have no objections to allowing the suggested options to be reloaded at runtime. 

@gwynne any thoughts?

2024-02-14 13:33 UTC, 0xTim commented on Sources/Vapor/HTTP/Server/HTTPServer.swift
> +                /// Copy the most up-to-date configuration.
Nit - this doesn't need to be a doc comment
```suggestion
                // Copy the most up-to-date configuration.
```

2024-02-14 13:33 UTC, 0xTim commented on Tests/VaporTests/ServerTests.swift
> +        let c = try? app.http.client.shared.execute(
Using an `XCTAssertThrows` may be better and checking the actual error in case we're missing the server actually being down etc

2024-02-14 13:47 UTC, dimitribouniol commented on Tests/VaporTests/ServerTests.swift
> +        let c = try? app.http.client.shared.execute(
Good call, fixed!

2024-02-14 14:02 UTC, gwynne commented on Sources/Vapor/HTTP/Server/HTTPServer.swift
> +                /// Copy the most up-to-date configuration.
I disagree with Tim here - I also use doc comments most of the time (though more for the inline formatting than for a font per se xD), I'd be more inclined to change the existing comments rather than the new one 🙂

2024-02-14 14:08 UTC, dimitribouniol commented on Sources/Vapor/HTTP/Server/HTTPServer.swift
> +                /// Copy the most up-to-date configuration.
Happy to revert them, let me know 🤣

2024-02-16 08:45 UTC, dimitribouniol commented on Sources/Vapor/HTTP/Server/HTTPServer.swift
> +                /// Copy the most up-to-date configuration.
Updated! Let me know if you'd rather them in a separate PR for commit history reasons, otherwise good to merge if you are happy with it.

2024-02-20 13:48 UTC, 0xTim approved these changes
Thanks!

2024-02-20 13:50 UTC, 0xTim commented
The failing test is a JWT issue that will be resolved tomorrow

2024-02-20 13:51 UTC, merged