Add Sendable conformances to avoid warnings on swift5.10
vapor/vapor pull request #3158
Opened 2024-03-12 06:38 UTC by sidepelican

Fix a number of warnings in Swift 5.10 like below.

![](https://github.com/vapor/vapor/assets/19257572/1e3daa24-8e01-4307-8b7b-8307adf2704d)

Fix simple issues that can be addressed by simply adding `Sendable`.

2024-03-14 00:07 UTC, 0xTim requested changes
Just need to unwind one of the route tests but otherwise LGTM!

2024-03-14 00:07 UTC, 0xTim commented on Sources/Development/routes.swift
> +    @Sendable func opaqueRouteTester(_ req: Request) async throws -> some AsyncResponseEncodable {
This unfortunately masks any issues as is the incorrect usage for functions (it's confusing and very counter intuitive) - could you remove?

2024-03-14 01:30 UTC, sidepelican commented on Sources/Development/routes.swift
> +    @Sendable func opaqueRouteTester(_ req: Request) async throws -> some AsyncResponseEncodable {
Ok. Removed. https://github.com/vapor/vapor/pull/3158/commits/e806eafb682f7a1030911293b548dc4cce3df3fb

2024-03-15 21:41 UTC, 0xTim approved these changes
Thanks!

2024-03-20 13:18 UTC, merged