Log actual port on startup
vapor/vapor pull request #3160
Opened 2024-03-13 22:00 UTC by bisgardo

Before this change, the application

```swift
let app = Application(.testing)
defer { app.shutdown() }
try app.server.start(hostname: nil, port: 0)
defer { app.server.shutdown() }
```

would log the following message *before* starting the server:

```
[Vapor] Server starting on http://127.0.0.1:0
```

After this change it instead logs a message like the following *after* starting the server:

```
[Vapor] Server started on [IPv4]127.0.0.1/127.0.0.1:57935
```

2024-03-13 22:04 UTC, bisgardo commented
I have no experience with this code base so I'm just guessing that it's safe to force unwrap `self.localAddress` after the server has successfully started.

I also realize that the log message is now less readable and doesn't include the protocol. This was just the simplest possible solution I could come up with. I'll be happy to change it.

Looking forward to your feedback.

2024-03-13 22:07 UTC, 0xTim requested changes

2024-03-13 22:07 UTC, 0xTim commented on Sources/Vapor/HTTP/Server/HTTPServer.swift
> +        configuration.logger.notice("Server started on \(self.localAddress!.description)")
As a general rule force unwrapping should be avoided. What I'd do is just move the whole block down and use the port from the local address and fall back to the existing behaviour if it's nil

2024-03-13 22:15 UTC, 0xTim commented on Sources/Vapor/HTTP/Server/HTTPServer.swift
> +        configuration.logger.notice("Server started on \(self.localAddress!.description)")
Hmm actually I remember why it's not like this currently - if it fails to bind to the specified you get no log message to help debug so we need the original message. I think we could probably change the original to an info and keep this one as notice.

What do you think @gwynne ?

2024-03-14 12:34 UTC, bisgardo commented on Sources/Vapor/HTTP/Server/HTTPServer.swift
> +        configuration.logger.notice("Server started on \(self.localAddress!.description)")
@0xTim just pushed a commit to address your first comment, didn't see the second one until now. Isn't the correct solution to ensure that an error is logged (including the configured port) when binding fails?

2024-03-14 12:38 UTC, bisgardo commented on Sources/Vapor/HTTP/Server/HTTPServer.swift
> +            }
Unsure if this is relevant. Can the actual hostname differ from the configured one?

2024-03-14 12:47 UTC, bisgardo commented on Sources/Vapor/HTTP/Server/HTTPServer.swift
> +        configuration.logger.notice("Server started on \(self.localAddress!.description)")
Or maybe just wrap the thrown error with one that includes `configuration.address`? For reference, if I try to start on a port that's already in use, the error is
```
failed: caught error: "bind(descriptor:ptr:bytes:): Address already in use (errno: 48)"
```

2024-03-14 12:50 UTC, bisgardo commented on Sources/Vapor/HTTP/Server/HTTPServer.swift
> +        /// Print starting message.
Out of curiosity, may I ask why comments are written with tripple slashes? Isn't that style for docstrings only?

2024-03-14 14:31 UTC, dimitribouniol commented on Sources/Vapor/HTTP/Server/HTTPServer.swift
> +        /// Print starting message.
I bet those are mine haha… Xcode renders them in a proportional font with formatting by default, which is easier on the eyes for prose comments

2024-03-14 14:33 UTC, dimitribouniol commented on Sources/Vapor/HTTP/Server/HTTPServer.swift
> +            }
My memory is spotty here, but the configuration, set in code, can be different than the listening port passed in the command line with the `listen` command

2024-03-20 18:10 UTC, 0xTim requested changes

2024-03-20 18:10 UTC, 0xTim commented on Sources/Vapor/HTTP/Server/HTTPServer.swift
> -        self.configuration.logger.notice("Server starting on \(addressDescription)")
Let's keep this but at the debug level

2024-03-24 21:54 UTC, bisgardo commented on Sources/Vapor/HTTP/Server/HTTPServer.swift
> +            addressDescription = "\(scheme)://\(hostname ?? Configuration.defaultHostname):\(port ?? Configuration.defaultPort)"
Same as before but a little more concise. At least I found `hostname ?? configuration.hostname` a little puzzling because that's always the same as just `configuration.hostname`.

2024-03-24 21:54 UTC, bisgardo commented on Sources/Vapor/HTTP/Server/HTTPServer.swift
> -        self.configuration.logger.notice("Server starting on \(addressDescription)")
Done.

2024-03-24 21:54 UTC, bisgardo commented on Sources/Vapor/HTTP/Server/HTTPServer.swift
> +            if let hostname = localAddress.hostname, let port = localAddress.port {
`.hostname` and `.port` are always (non) `nil` together.

Is it relevant to do the same for `pathname` (for Unix sockets)?

2024-03-24 21:54 UTC, bisgardo commented on Sources/Vapor/HTTP/Server/HTTPServer.swift
> +                addressDescription = "\(scheme)://\(hostname):\(port)"
Don't know about this? We could also make `addressDescription` a method on `Configuration`.

2024-03-25 04:36 UTC, 0xTim commented on Sources/Vapor/HTTP/Server/HTTPServer.swift
> +                addressDescription = "\(scheme)://\(hostname):\(port)"
I suggest we just have a new variable to avoid the mutating variable that might get confusing later on

2024-03-25 04:37 UTC, 0xTim commented on Sources/Vapor/HTTP/Server/HTTPServer.swift
> +            if let hostname = localAddress.hostname, let port = localAddress.port {
We definitely want to print the socket address at the notice log level once the server has started

2024-03-25 04:39 UTC, 0xTim requested changes
Thanks! Just a couple of nits left

2024-03-25 04:39 UTC, 0xTim commented on Sources/Vapor/HTTP/Server/HTTPServer.swift
> +        var addressDescription: String
Let's have a separate variable for pre and post app startup

2024-03-26 22:16 UTC, bisgardo commented on Sources/Vapor/HTTP/Server/HTTPServer.swift
> +            if let hostname = localAddress.hostname, let port = localAddress.port {
That also happened with this. The question is whether it's relevant to patch unix socket addres with the actual pathname (i.e. whether it can differ from the configured one). I added that in the latest commit, but can remove it again if it's irrelevant.

2024-03-26 22:18 UTC, bisgardo commented on Sources/Vapor/HTTP/Server/HTTPServer.swift
> +                addressDescription = "\(scheme)://\(hostname):\(port)"
I hope you agree that a computed property on Configuration is cleaner than duplicating the code block, so I did that. Is that ok?

2024-04-10 10:20 UTC, bisgardo commented
Ping @0xTim :)

2024-04-15 18:15 UTC, bisgardo commented
@0xTim Is there anything that needs to change before this can get merged? If you disagree with extracting `addressDescription` I can inline it, no problem.

2024-04-19 23:35 UTC, 0xTim requested changes
One minor change then good to go!

2024-04-19 23:35 UTC, 0xTim commented on Sources/Vapor/HTTP/Server/HTTPServer.swift
> +        public var addressDescription: String {
Let's make this private, we can always open it up if needed but since we only use it internally it's better to keep it like that for now

2024-04-22 11:00 UTC, bisgardo commented on Sources/Vapor/HTTP/Server/HTTPServer.swift
> +        public var addressDescription: String {
Done (assuming you meant non-public and not actually `private` as that doesn't compile).

2024-04-23 12:09 UTC, 0xTim requested changes
Sorry one last thing to add - can you add a test for the configuration? Essentially run the server set to port 0 and then try and read the port from the configuration and make sure it isn't 0

2024-04-23 18:53 UTC, 0xTim approved these changes
Thanks!

2024-04-23 23:44 UTC, 0xTim commented
@bisgardo the new test is failing

2024-04-24 21:31 UTC, bisgardo commented
> @bisgardo the new test is failing

It was an existing test, not the new one. I've pushed a fix.

2024-04-26 19:56 UTC, merged