Provide AsyncFileStreaming API
vapor/vapor pull request #3184
Opened 2024-04-30 23:27 UTC by 0xTim

Builds on the work of #2998, #3170 and #3167 to provide a full async streaming API that can be used in Swift Concurrency environments

2024-04-30 23:28 UTC, 0xTim commented
The stream file functions could use some tidying up as there's a lot of duplicated code there

2024-05-07 22:29 UTC, gwynne requested changes
A few nits about behavior

2024-05-07 22:29 UTC, gwynne commented on Sources/Vapor/HTTP/Server/HTTPServerHandler.swift
> +                            try await stream.callback(ErrorBodyStreamWriter(eventLoop: request.eventLoop, error: error))
Probably better to use `try?` here rather than let errors propagate, we're already in an error-handling path as it is. (Yes, I realize it doesn't really matter with this writer, but as a matter of good form.)

2024-05-07 22:29 UTC, gwynne commented on Sources/Vapor/HTTP/Server/HTTPServerHandler.swift
>      var error: Error
These don't need to be mutable 🙄

2024-05-07 22:29 UTC, gwynne commented on Sources/Vapor/Response/Response+Body.swift
> +private final class ResponseBodyCollector: BodyStreamWriter, AsyncBodyStreamWriter, @unchecked Sendable {
Really, this should look a lot more similar to the `ChannelResponseBodyStream` writer - at least inasmuch as it should maintain enough state to defensively complain on API misuse and so forth. But I don't think it's worth holding up this PR further over it.

2024-05-07 22:29 UTC, gwynne commented on Sources/Vapor/Utilities/FileIO.swift
> +            )
```suggestion
        self.request.eventLoop.makeFutureWithTask {
            guard let fileSize = try await FileSystem.shared.info(forFileAt: .init(path))?.size else {
                throw Abort(.internalServerError)
            }
            try await self.read(
                path: path,
                fromOffset: 0,
                byteCount: Int(fileSize),
                chunkSize: chunkSize,
                onRead: onRead
            ).get()
        }
```
Saves at least one extra thread hop, especially in the case of the file not existing (where it saves more like two or three).

2024-05-07 22:29 UTC, gwynne commented on Sources/Vapor/Utilities/FileIO.swift
> +            return Response(status: .internalServerError)
Wouldn't we prefer to `throw Abort(.internalServerError)` here to get the benefit of any error middleware?

2024-05-07 22:29 UTC, gwynne commented on Sources/Vapor/Utilities/FileIO.swift
> +            return response
Again, shouldn't we throw?

2024-05-07 22:29 UTC, gwynne commented on Sources/Vapor/Utilities/FileIO.swift
> +                    return response
Again, shouldn't we throw?

2024-05-07 22:35 UTC, 0xTim commented on Sources/Vapor/Utilities/FileIO.swift
> +            return Response(status: .internalServerError)
Yeah no idea why I picked that

2024-05-07 23:50 UTC, gwynne approved these changes

2024-05-07 23:57 UTC, merged