Async Serve Command
vapor/vapor pull request #3190
Opened 2024-05-10 16:56 UTC by 0xTim

Migrate `ServeCommand` to an `AsyncCommand` to enable proper custom executor support and remove any calls to `wait()`

2024-05-10 16:57 UTC, 0xTim commented
Need to work out why the configuration has broken in the tests

2024-05-10 16:59 UTC, 0xTim commented
Verified this works with https://github.com/vapor/template/pull/131/files with Leaf and Fluent and all working

2024-05-11 00:46 UTC, gwynne commented on Sources/XCTVapor/XCTApplication.swift
> +                let response = try await client.execute(request: clientRequest).get()
Why is `.get()` needed here? `HTTPClient` has an async version of `execute()` (with different argument labels).

2024-05-11 00:48 UTC, gwynne requested changes
One nit

2024-05-13 10:54 UTC, 0xTim commented on Sources/XCTVapor/XCTApplication.swift
> +                let response = try await client.execute(request: clientRequest).get()
Done

2024-05-13 10:55 UTC, 0xTim commented
@gwynne this is ready for you now I think

2024-05-13 14:46 UTC, gwynne approved these changes

2024-05-13 15:07 UTC, merged