Percent-encode `$` in URLEncodedFormEncoder
vapor/vapor pull request #3192
Opened 2024-05-13 12:52 UTC by ptoffy

Solves #3173

2024-05-13 12:55 UTC, 0xTim requested changes

2024-05-13 12:55 UTC, 0xTim commented on Sources/Vapor/URLEncodedForm/URLEncodedFormSerializer.swift
> +        allowed.remove(charactersIn: "?&=[];+$")
We should inverse this completely as per https://url.spec.whatwg.org/#application-x-www-form-urlencoded-percent-encode-set.

Essentially if it _isn't_ alphanumeric, `*`, `-`, `.` or `_` we should encode it

2024-05-13 17:14 UTC, ptoffy commented on Sources/Vapor/URLEncodedForm/URLEncodedFormSerializer.swift
> +        var allowed = CharacterSet.alphanumerics
I'm honestly not sure why this is allowing `[` and `]`

2024-05-13 17:15 UTC, ptoffy commented on Sources/Vapor/URLEncodedForm/URLEncodedFormSerializer.swift
> +        allowed.insert(charactersIn: "*-._")
I'm honestly not sure why this is allowing `[` and `]`

2024-05-20 15:02 UTC, 0xTim approved these changes

2024-05-20 15:12 UTC, gwynne commented on Tests/VaporTests/URLEncodedFormTests.swift
> +                Date(timeIntervalSince1970: 50000),
Honestly, turn down the settings on your code formatter, this is a change for the worse 🤣

2024-05-20 15:13 UTC, gwynne approved these changes

2024-05-20 16:06 UTC, merged