asyncBoot will no longer try booting server again if it is already booted
vapor/vapor pull request #3195
Opened 2024-05-19 20:35 UTC by RussBaz

The synchronous `boot` function skips running the lifecycle handlers if the server is already booted. However, the async version ignored this check. I have added a small fix to add this check again.

2024-05-19 21:45 UTC, gwynne commented on Sources/Vapor/Application.swift
> +
```suggestion
        guard !self.isBooted.withLockedValue({
            var result = true
            swap(&$0, &result)
            return result
        }) else {
            return
        }

2024-05-20 17:06 UTC, RussBaz commented on Sources/Vapor/Application.swift
> +
I agree, it made the code more concise and efficient. I merged the suggestion. Not only that, but I even learned that Swift has an inbuilt `swap` function. 😄  Although, I think it is now less obvious what this snippet does. I have added a comment to help with that a bit.

2024-05-21 14:25 UTC, 0xTim requested changes
Thanks! Could you add a test to ensure this works?

```swift
    func testBootDoesNotTriggerHandlerMultipleTimes() throws {
        let app = Application(.testing)
        defer { app.shutdown() }
        
        final class Handler: LifecycleHandler, Sendable {
            let bootCount = NIOLockedValueBox(0)
            func willBoot(_ application: Application) throws {
                bootCount.withLockedValue { $0 += 1 }
            }
        }
        
        let handler = Handler()
        app.lifecycle.use(handler)
        
        try app.boot()
        try app.boot()

        XCTAssertEqual(handler.bootCount.withLockedValue({ $0 }), 1)
    }
    
    func testAsyncBootDoesNotTriggerHandlerMultipleTimes() async throws {
        let app = try await Application.make(.testing)
        
        final class Handler: LifecycleHandler, Sendable {
            let bootCount = NIOLockedValueBox(0)
            func willBoot(_ application: Application) throws {
                bootCount.withLockedValue { $0 += 1 }
            }
        }
        
        let handler = Handler()
        app.lifecycle.use(handler)
        
        try await app.asyncBoot()
        try await app.asyncBoot()

        XCTAssertEqual(handler.bootCount.withLockedValue({ $0 }), 1)
        
        try await app.asyncShutdown()
    }
```

In ApplicationTests should work

2024-05-21 20:13 UTC, RussBaz commented
Done. Please have a look again.

2024-05-21 20:14 UTC, 0xTim approved these changes
Thanks!

2024-05-21 20:18 UTC, merged