Exclude Query and Fragment from URI semicolon fix on Linux
vapor/vapor pull request #3201
Opened 2024-05-28 09:06 UTC by fred-sch

On Linux, `URLComponents` does not have 100% the same behavior like on macOS. Vapor accounts for [this unfixed bug](https://github.com/apple/swift-corelibs-foundation/issues/3352) by replacing percent-encoded semicolon `%3B` with `;` in `URI`s.

This is however not fully correct, because if a URI contains a percent encoded semicolon, this might have a different meaning, than when it is not percent encoded, compare the following sentence from RFC 3986:
```
A percent-encoding mechanism is used to represent a data octet in a
component when that octet's corresponding character is outside the
allowed set or is being used as a delimiter of, or within, the component.
```

This PR aims to limit the impact of the required semicolon fix by ensuring that query and fragments are not unnecessarily and incorrectly modified. 

Hopefully, in a future with the new swift-foundation this fix will not be needed anymore. But for now it would solve an issue on our side which is related to the concept of a signed request.

2024-05-28 09:20 UTC, fred-sch commented
The failing test indicates, that the faulty `URLComponents` behavior also affects macOS-13. Unfortunately, I cannot really reproduce that locally.

2024-05-29 08:06 UTC, gwynne requested changes
Good catch on the issue, some nits regarding the fix

2024-05-29 08:06 UTC, gwynne commented on Sources/Vapor/Utilities/URI.swift
> +            return modify[modify.startIndex..<replaceUntil].replacingOccurrences(of: "%3B", with: ";") + modify[replaceUntil..<modify.endIndex]
```suggestion
            let string = self.components?.string ?? ""
            return string.replacingOccurrences(
                of: "%3B", with: ";",
                options: .literal, // N.B.: `rangeOfPath` never actually returns `nil`
                range: self.components?.rangeOfPath ?? (string.startIndex..<string.startIndex)
            )
```

2024-05-29 08:06 UTC, gwynne commented on Sources/Vapor/Utilities/URI.swift
> +}()
```suggestion
private let urlPathAllowedIsBroken: Bool = {
    CharacterSet.urlPathAllowed != CharacterSet.urlCorrectPathAllowed
}()
```

2024-05-29 08:06 UTC, gwynne commented on Tests/VaporTests/URITests.swift
> +        )
```suggestion
    func testSemicolonIsNotEncodedInPathComponent() {
        XCTAssertURIString(
            "https://user:pass@vapor.codes:1234/foo;?bar=abcd%3B%C3%A4%2B#qux%3B",
            hasScheme: "https",
            hasUserinfo: "user:pass",
            hasHost: "vapor.codes",
            hasPort: 1234,
            hasPath: "/foo;",
            hasQuery: "bar=abcd%3B%C3%A4%2B",
            hasFragment: "qux%3B"
        )
```
^ so that we test that we're _specifically_ only mutating the path component.

2024-05-29 09:09 UTC, fred-sch commented on Sources/Vapor/Utilities/URI.swift
> +            return modify[modify.startIndex..<replaceUntil].replacingOccurrences(of: "%3B", with: ";") + modify[replaceUntil..<modify.endIndex]
I totally agree that this is the better solution!

2024-05-29 09:11 UTC, fred-sch commented on Tests/VaporTests/URITests.swift
> +        )
I also slightly adapted the query so that we test that we can have `;` and `%3B` at the same time:

```
hasQuery: "bar=abcd%3B%C3%A4%2B;efg",
```

2024-05-29 09:41 UTC, gwynne approved these changes
Looks great, thanks!

2024-05-29 09:41 UTC, merged