Support Swift 6
vapor/vapor pull request #3209
Opened 2024-06-21 23:59 UTC by 0xTim

Fully support Swift 6:

* Adds a Swift 6 manifest
* Fixes the last Sendable warning
* Fixes a deprecation

> [!WARNING]  
> This can't be merged until https://github.com/swiftlang/swift/pull/74614 is shipped in a Swift 6 toolchain

2024-06-22 01:19 UTC, gwynne commented on Sources/Vapor/HTTP/Headers/HTTPHeaderCacheControl.swift
> +        private static let prefix: [String: WritableKeyPath<Self, Int?> & Sendable] = [
Might want to get rid of my junkier workaround at the bottom of the file if this works.

2024-06-22 01:20 UTC, gwynne commented on Sources/Vapor/Content/PlaintextEncoder.swift
> +#elseif swift(>=5.7.2)
Please just bump the base manifest to 5.8 already.

2024-06-22 01:20 UTC, gwynne requested changes
per comments

2024-08-20 18:50 UTC, 0xTim commented
We're not going to introduce a 6.0 manifest for Vapor 4

2024-08-20 18:50 UTC, closed without merging