fix `HTTPMethod.RAW(value: String)` string representation
vapor/vapor pull request #3249
Opened 2024-11-01 15:03 UTC by RandomHashTags

Should fix #3248

2024-11-01 15:24 UTC, gwynne requested changes

2024-11-01 15:24 UTC, gwynne commented on Sources/Vapor/HTTP/HTTPMethod+String.swift
>          }
The correct fix to this is to use the `rawValue` accessor provided by NIO (ostensibly, this `string` accessor shouldn't exist at all - it's only here because NIO didn't add `rawValue` until a few months after Tanner added this and he never went back to clean it up - but it's public API in Vapor so we can't just remove it, unfortunately).
```suggestion
        self.rawValue
```

2024-11-01 15:40 UTC, RandomHashTags commented
Maybe remove this file and replace its usages with the `rawValue` in a future patch?

2024-11-01 15:43 UTC, gwynne commented
> Maybe remove this file and replace its usages with the `rawValue` in a future patch (or this one 👀 )?

Unfortunately we can't, at least not in Vapor 4 - it's preexisting public API, removing it would be a semver-major break.

2024-11-01 15:50 UTC, 0xTim commented on Sources/Vapor/HTTP/HTTPMethod+String.swift
> +        self.rawValue
We should probably add a deprecation to the above as well

2024-11-01 16:15 UTC, RandomHashTags commented on Sources/Vapor/HTTP/HTTPMethod+String.swift
> +        self.rawValue
Added

2024-11-01 17:32 UTC, gwynne approved these changes

2024-11-03 19:32 UTC, 0xTim commented on Sources/Vapor/HTTP/HTTPMethod+String.swift
> +    @available(*, deprecated, message: "Use 'rawValue' instead")
```suggestion
    @available(*, deprecated, renamed: "rawValue")
```

2024-11-03 19:32 UTC, 0xTim approved these changes

2024-11-03 19:40 UTC, merged