Adds swift-distributed-tracing and TracingMiddleware
vapor/vapor pull request #3253
Opened 2024-11-12 06:01 UTC by NeedleInAJayStack

This adds support for `swift-distributed-tracing` and adds a `TracingMiddleware` type. This type will create a span for each wrapped request, and apply a standard set of span attributes according to OTEL standards.

For background, see: https://github.com/vapor/vapor/issues/3033

2024-11-12 06:08 UTC, NeedleInAJayStack commented
As noted in the [issue](https://github.com/vapor/vapor/issues/3033) the `TracingMiddlware` span unfortunately will not cross EventLoopFuture boundaries. One approach could be to add a `rootSpan` stored property onto `Request` so that downstream spans can manually set their parent (as explained [`here`](https://github.com/apple/swift-distributed-tracing/pull/153/files)). I'm definitely open to ideas though!

@slashmo, you asked to be pinged when an implementation was started. I'd love your thoughts!

2024-11-21 17:20 UTC, 0xTim requested changes
Thank you for this! This is great.

Some minor comments but almost ready to go

2024-11-21 17:20 UTC, 0xTim commented on Sources/Vapor/Middleware/TracingMiddleware.swift
> +                // Opt-in
Let's remove this if we're not going to have any here

2024-11-21 17:20 UTC, 0xTim commented on Tests/VaporTests/MiddlewareTests.swift
> +final class TestTracer: Tracer {
Can we pull this out into a separate file?

2024-11-21 17:20 UTC, 0xTim commented on Tests/VaporTests/MiddlewareTests.swift
> +        try await app.testable().test(.GET, "/testTracing") { res in
I think if you do `app.testable(method: .running(port: 0))` that will make a real HTTP request to give us more attributes below

2024-11-21 17:20 UTC, 0xTim commented on Tests/VaporTests/MiddlewareTests.swift
> +        XCTAssertEqual(span.attributes["user_agent.original"]?.toSpanAttribute(), nil)
We could use the `beforeRequest` closure to set the user agent header to check this

2024-11-22 06:23 UTC, NeedleInAJayStack commented on Sources/Vapor/Middleware/TracingMiddleware.swift
> +                // Opt-in
Whoops - this was left over from when I included a few of them. I've removed.

2024-11-22 06:23 UTC, NeedleInAJayStack commented on Tests/VaporTests/MiddlewareTests.swift
> +final class TestTracer: Tracer {
Yes, definitely. I've moved it to a new file at `Utilities/TestTracer.swift`

2024-11-22 06:24 UTC, NeedleInAJayStack commented on Tests/VaporTests/MiddlewareTests.swift
> +        XCTAssertEqual(span.attributes["user_agent.original"]?.toSpanAttribute(), nil)
Good idea - done.

2024-11-22 07:16 UTC, NeedleInAJayStack commented
One followup question - Given that [AsyncMiddleware uses EventLoopFuture.get](https://github.com/vapor/vapor/blob/60144400f627faa98e31914a1272337a69450bd8/Sources/Vapor/Concurrency/AsyncMiddleware.swift#L23), a span created in the `next` route handler won't be recognized as a child span of the one created in the new `TracingMiddleware`. 

What do you think about providing a `Request.span: Span?` property in which the user can manually propagate the `TracingMiddleware` span (I have a PR in to add documentation on how to do this in a NIO environment [here](https://github.com/apple/swift-distributed-tracing/pull/153/files#diff-873fc97b1dc4983f3375ba329a853b5c918784df2851ec34890134754700d76eR233))

2024-11-22 18:21 UTC, 0xTim approved these changes
This looks good!

2024-11-22 18:22 UTC, 0xTim commented
@NeedleInAJayStack yes we either need to do that for the user (so at the point where we bridge between worlds do it in Vapor) or add the property. I'd be in favour of doing it in Vapor to make it easy where possible.

2024-11-24 19:44 UTC, NeedleInAJayStack commented
> @NeedleInAJayStack yes we either need to do that for the user (so at the point where we bridge between worlds do it in Vapor) or add the property. I'd be in favour of doing it in Vapor to make it easy where possible.

Sounds good. I actually did both because internally propogating in Vapor needs the property anyway.

I've added the `Request.serviceContext` property in [this commit](https://github.com/vapor/vapor/pull/3253/commits/cbbf68852608161dd276e8a0be28bddaa2e7bd74), and automatically injected the service context into each route & middleware callback in [this commit](https://github.com/vapor/vapor/pull/3253/commits/865efcecf31992b1aa9bf39e80fcf497826d3a22). The pattern of middlewares ["setting and restoring" the `Request.serviceContext`](https://github.com/vapor/vapor/pull/3253/commits/cbbf68852608161dd276e8a0be28bddaa2e7bd74#diff-e86201a80ba1c380d64197003bb66a71212cd8aba3e18fbccdc39d70f4b5da70R17) should probably be copied by any users that write middlewares that create spans in order for their Route closures to nest under the correct span.

2024-12-01 12:21 UTC, 0xTim approved these changes
I think I'm good with this, just want to loop in @gwynne for a second look

2024-12-01 12:21 UTC, 0xTim commented on Sources/Vapor/HTTP/BasicResponder.swift
> +            return try ServiceContext.withValue(request.serviceContext) {
My one concern with this is a potential performance impact and whether we should put it behind a flag or not, given most people won't use it.

Thoughts @gwynne

2024-12-01 13:38 UTC, gwynne commented on Sources/Vapor/HTTP/BasicResponder.swift
> +            return try ServiceContext.withValue(request.serviceContext) {
I agree - this should be behind a flag. I'm uneasy enough with including swift-distributed-tracing as a dependency, on the same principle.

2024-12-01 13:45 UTC, 0xTim commented on Sources/Vapor/HTTP/BasicResponder.swift
> +            return try ServiceContext.withValue(request.serviceContext) {
I think I'm fine to add the dependency, but I think putting it behind a flag would be the right thing to do

2024-12-01 16:58 UTC, NeedleInAJayStack commented on Sources/Vapor/HTTP/BasicResponder.swift
> +            return try ServiceContext.withValue(request.serviceContext) {
This was actually my effort to address:

> I'd be in favour of doing it in Vapor to make it easy where possible.

If there are performance concerns, I'd suggest that we remove all the `ServiceContext.withValue(request.serviceContext) {` calls from this PR, and let the user manage the span/serviceContext instead of introducing a flag. That way, the user can be more specific and only incur the `Request` property and `Task.local` overhead to specifically where they need tracing.

For example, the user could just pass in the `req.serviceContext` into a span manually:

```swift
app.routes.get("hello") { req in
    try await withSpan(name: "hello-span", context: req.serviceContext) { span in
        try await doHello()
    }
}
```

They can always manage the `req.serviceContext` manually as well if downstream methods need it set:

```swift
app.routes.get("hello") { req in
    parentSpan = req.serviceContext
    let hello = try await withSpan(name: "hello-span", context: req.serviceContext) { span in
        req.serviceContext = span.context
        defer {
            req.serviceContext = parentSpan
        }
        return doHello()
    }
    return hello
}
```

Does that make sense to you guys? What do you think?

2024-12-02 10:14 UTC, ktoso commented on Sources/Vapor/HTTP/BasicResponder.swift
> +            return try ServiceContext.withValue(request.serviceContext) {
Two things:
- We really need to stop worrying about adding the dependency. This is "the" API package, the same way as logging and metrics, and frameworks _should_ adopt it.
- If you're seeing some performance hit from the no-op tracer I think it's fine to have this be opt-in. A NoOp tracer is optimized to be really fast and "do nothing" but it'll have to read the bootstrapped value so yes I think it's fine to avoid the lookup if you want and just document to folks "if you want to use distributed tracing, enable <<something>>" 👍

2024-12-02 10:16 UTC, ktoso commented on Package.swift
> +        .package(url: "https://github.com/apple/swift-distributed-tracing.git", from: "1.0.0"),
I'd probably say `1.1.0`, we did some language version specific adjustments in the 1 series.

2024-12-02 10:20 UTC, ktoso commented on Sources/Vapor/Middleware/TracingMiddleware.swift
> +/// See https://opentelemetry.io/docs/specs/semconv/http/http-spans/
LGTM, and OK to not use the swift-distributed-tracing-extras repo -- as we'll want to change how we have organized all those repos. I think what you're doing here is safer in face of the not-stable-extras repo.

We'll want to make a stable repo that is versioned along with the `semconv`'s version, but we don't have it yet. So this is LGTM as-is

2024-12-02 10:23 UTC, ktoso approved these changes
Thank you for the adoption PR, I think this looks good! The attributes look ok as well.

@0xTim it'd be lovely to accept this and we should follow up updating the tracing repo with info that vapor supports tracing (as well as hummingbird) 👍

2024-12-04 06:51 UTC, NeedleInAJayStack commented on Package.swift
> +        .package(url: "https://github.com/apple/swift-distributed-tracing.git", from: "1.0.0"),
Sounds good, I updated to 1.1.0.

2024-12-10 05:13 UTC, NeedleInAJayStack commented on Sources/Vapor/HTTP/BasicResponder.swift
> +            return try ServiceContext.withValue(request.serviceContext) {
Hey @0xTim, just let me know what you think here. I'm happy to either add a tracing flag or remove the `ServiceContext.withValue` calls - whichever you prefer.

2024-12-12 11:32 UTC, 0xTim commented on Sources/Vapor/HTTP/BasicResponder.swift
> +            return try ServiceContext.withValue(request.serviceContext) {
@NeedleInAJayStack ok I think me and @gwynne are agreed that a flag is the way to go to avoid all the copies as we switch boundaries

2024-12-13 06:47 UTC, NeedleInAJayStack commented on Sources/Vapor/HTTP/BasicResponder.swift
> +            return try ServiceContext.withValue(request.serviceContext) {
Sounds good to me! In [this commit](https://github.com/vapor/vapor/pull/3253/commits/428db1ac7f3c4276a25f993d08e09198e716c8cb) I added an `Application.traceAutoPropogation` flag that defaults to false. When enabled, trace spans are propogated automatically, incurring the copying overhead, and when disabled they are not.

I kinda took a guess on where the flag should be. Let me know if you where thinking of it happening somewhere else and I'd be happy to change. Thanks!

2024-12-17 19:51 UTC, 0xTim requested changes
Thanks! This looks good - just one requested change just to avoid accessing the lock several times

2024-12-19 06:52 UTC, NeedleInAJayStack commented on Sources/Vapor/Request/Request.swift
> +        if self.application.traceAutoPropagation {
Oh yeah, absolutely. Good call. I've changed it.

2024-12-20 02:03 UTC, 0xTim approved these changes
Thanks for this! I think we're good to go

2024-12-20 02:36 UTC, gwynne approved these changes
LGTM

2024-12-20 10:18 UTC, merged