SwiftTesting compatibility
vapor/vapor pull request #3257
Opened 2024-11-20 14:51 UTC by MahdiBM

2024-11-20 18:58 UTC, gwynne commented
> The API breakage failure is incorrect as far as I can tell.

Correct - the API breakage checker, along with all its many other flaws, can't see through `@_exported` to tell that you moved the names between modules and reexported them from the original.

2024-11-20 22:31 UTC, MahdiBM commented on Sources/VaporTesting/+TestingApplicationTester.swift
> +    @available(*, noasync, message: "Use the async method instead.")
readded these 3 noasync functions as well

2024-12-01 13:44 UTC, 0xTim requested changes
Looks good overall, just some changes since this is a new API and no point adding on tech debt where not needed

2024-12-01 13:44 UTC, 0xTim commented on Sources/VaporTesting/+TestingApplicationTester.swift
> +    @available(*, noasync, message: "Use the async method instead.")
Do we actually need these? Given this is a new API, why not just offer the async variants only?

2024-12-01 13:44 UTC, 0xTim commented on Sources/XCTVapor/XCTVaporTests.swift
> -public var app: (@Sendable () throws -> Application)! {
I think we should keep this here and not offer it as part of the test utils. Anyone using Swift testing shouldn't be using this global

2024-12-01 13:51 UTC, 0xTim commented on Sources/VaporTesting/+TestingApplicationTester.swift
> +    @available(*, noasync, message: "Use the async method instead.")
Yeah the compiler gets really confused by these forcing the closure to be marked as `async` so this should solve it

2024-12-01 14:01 UTC, 0xTim commented on Tests/VaporTests/VaporTesting.swift
> +        defer { app.shutdown() }
We should make this async and use the with syntax given that's what we want to push people towards (and test it etc)

2024-12-02 13:56 UTC, MahdiBM commented on Tests/VaporTests/VaporTesting.swift
> +        try app.testable().test(.POST, "/decode") { req in
hmm interesting how it works anyway although i haven't imported XCTVapor.

2024-12-02 14:14 UTC, MahdiBM commented
@0xTim interesting find: Swift struggles to find the correct function even when i haven't imported XCTVapor at all.
I had to do something (add a parameter name) to help Swift disambiguate between the functions: https://github.com/vapor/vapor/pull/3257/commits/da428df9fcc06b10c7e75451c718a7724f8eb850

2024-12-07 03:33 UTC, 0xTim commented
I'm not completely happy with the added parameter. If you don't have XCTVapor imported it shouldn't be able to see those functions so I'm not sure why it would fail. What was the actual error message?

2024-12-08 17:58 UTC, MahdiBM commented
@0xTim 
> If you don't have XCTVapor imported it shouldn't be able to see those functions so I'm not sure why it would fail. What was the actual error message?

On another project it works fine, but here in the VaporTesting test file, I could confirm that it picks the XCT function, although I haven't imported XCTVapor.

2024-12-09 19:44 UTC, 0xTim commented
> On another project it works fine, but here in the VaporTesting test file, I could confirm that it picks the XCT function, although I haven't imported XCTVapor.

That's probably just SwiftPM being weird because it's the same module. Feel free to namespace the calls in the tests if needed to make it work

2024-12-20 18:47 UTC, 0xTim requested changes
Last couple of changes

2024-12-20 18:47 UTC, 0xTim commented on Sources/VaporTesting/TestingApplicationTester.swift
> +    @available(*, noasync, message: "Use the async method instead.")
This is a new module right? So we can removed the deprecation and only have the async variant

2024-12-20 18:47 UTC, 0xTim commented on Sources/VaporTesting/TestingApplicationTester.swift
> +    @available(*, noasync, message: "Use the async method instead.")
See above

2024-12-20 18:52 UTC, MahdiBM commented on Sources/VaporTesting/TestingApplicationTester.swift
> +    @available(*, noasync, message: "Use the async method instead.")
Ah right

2024-12-20 19:54 UTC, MahdiBM commented on Sources/VaporTesting/TestingApplicationTester.swift
> +    @available(*, noasync, message: "Use the async method instead.")
actually i had this change, just forgot to commit

2024-12-21 01:26 UTC, 0xTim approved these changes

2024-12-21 01:33 UTC, merged