Validation API | `Custom` Validator
vapor/vapor pull request #3263
Opened 2024-12-04 10:47 UTC by WilliamFernsV3

Resolves this issue I created the other day: https://github.com/vapor/vapor/issues/3261

**Problem**:

The Validation API allows you to create custom validators. It works, and it is good enough. In some cases however, extending the Validation API is not needed, as the validation is only for one `Content` object, meaning it will only be used once. I also find it more complex to extend the Validation API. 

**Solution**:

In some if not most cases where a user wants to add some custom validation, they can now use the `Custom` validator. It is simpler, and the implementation is shorter.

Here is how it would look like before if a user wants to create a custom validator:

```swift
extension Validator where T == String {
    public static var usPhoneNumber: Validator<T> {
        .init { input -> ValidatorResult in
            let stripped = input
                .replacingOccurrences(of: "(", with: "")
                .replacingOccurrences(of: ")", with: "")
                .replacingOccurrences(of: "-", with: "")
                .replacingOccurrences(of: " ", with: "")
                .replacingOccurrences(of: "+1", with: "")
            let numbersSet = CharacterSet(charactersIn: "0123456789")
            let strippedSet = CharacterSet(charactersIn: stripped)

            guard stripped.count == 10 else {
                return ValidatorResults.USPhoneNumber(isValidPhoneNumber: false)
            }
            guard strippedSet.isSubset(of: numbersSet) else {
                return ValidatorResults.USPhoneNumber(isValidPhoneNumber: false)
            }
            return ValidatorResults.USPhoneNumber(isValidPhoneNumber: true)
        }
    }
}

extension ValidatorResults {
    /// `ValidatorResult` of a validator that validates whether a `String` is a valid US phone number.
    public struct USPhoneNumber {
        /// The input is a valid state
        public let isValidPhoneNumber: Bool
    }
}

extension ValidatorResults.USPhoneNumber: ValidatorResult {
    public var isFailure: Bool {
        !self.isValidPhoneNumber
    }

    public var successDescription: String? {
        "is a valid phone number"
    }

    public var failureDescription: String? {
        "is not a valid phone number"
    }
}
```

Here is what you can do now with the changes made in this PR:

```swift
v.add(
    "email",
        as: String?.self,
    is: .custom(
        validationDescription: "Validates whether email domain is 'tanner.xyz'."
    ) { email in
            if let email {
                let parts = email.split(separator: "@")
                return parts[parts.count-1] == "tanner.xyz"
            }
            return true
    }
)
```

**Changes**:

- [ ] Created `Custom` validator
- [ ] Updated validations tests to test `Custom` validator.

**Upcoming Changes**:

I will do the following in the following few days:

- [ ] Update Vapor Docs to show how the `Custom` validator can be used.

**Title**: Validation API | `Custom` Validator
**Body**: Simpler and shorter approach for creating custom validations using Vapor Validation API.

2024-12-04 10:51 UTC, WilliamFernsV3 reviewed
Overall great.

2024-12-04 10:51 UTC, WilliamFernsV3 commented on Tests/VaporTests/ValidationTests.swift
> +                                let parts = email.split(separator: "@")
Look good.

2024-12-05 05:17 UTC, WilliamFernsV3 commented
@0xTim , what do you think?

2024-12-05 06:38 UTC, WilliamFernsV3 commented
Just documenting how to fixd CodeQL job for Ubuntu-22.04 failing. Helping out to make this job pass will be appreciated.

Error:
```
Encountered a fatal error while running "/opt/hostedtoolcache/CodeQL/2.19.4/x64/codeql/codeql database finalize --finalize-dataset --threads=4 --ram=14567 /home/runner/work/_temp/codeql_databases/swift". Exit code was 32 and last log line was: CodeQL detected code written in Swift but this run didn't build any of it, or CodeQL could not process any of it. Ensure that you have provided manual build steps (see https://docs.github.com/en/code-security/code-scanning/creating-an-advanced-setup-for-code-scanning/codeql-code-scanning-for-compiled-languages#about-specifying-build-steps-manually) for Swift between the 'init' and 'analyze' Actions, and check the workflow run logs (see https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflows/using-workflow-run-logs). For more information, review our troubleshooting guide at https://gh.io/troubleshooting-code-scanning/no-source-code-seen-during-build . See the logs for more details.
```

This isn't happening on other PRs. So it must have to do with the new files I created. It seems like it didn't include it in the build. 

As indicated in the error, [this](https://docs.github.com/en/code-security/code-scanning/troubleshooting-code-scanning/no-source-code-seen-during-build) is most likely the issue. 

I am going through each troubleshooting step:

1. No supported languages. This cannot be the case. CodeQL supports compiled languages like Swift.
2. No analyzable in detected languages. This is not the case. The CodeQL workflow explicitly specify the languages it should analyze. [See here](https://github.com/vapor/vapor/blob/3aeeb6fab5112fb10ce699b5a80207e5cf571c32/.github/workflows/test.yml#L61-L73)
3. Compiling code failed. This is false. You can see this in the last few lines [here](https://github.com/vapor/vapor/actions/runs/12173539633/job/33954062453?pr=3263#step:6:4852)
4. Cached components not detected. I don't think this is the case, because package was build entirely without any caching as seen in [the logs](https://github.com/vapor/vapor/actions/runs/12173539633/job/33954062453). CodeQL has some caching involved, like [dependency caching](https://docs.github.com/en/code-security/code-scanning/creating-an-advanced-setup-for-code-scanning/codeql-code-scanning-for-compiled-languages#about-dependency-caching-for-codeql). Maybe this can be the cause. Will come back to this.
5. Compilation not between `init` and `analyze` steps. This is false. [See here](https://github.com/vapor/vapor/blob/3aeeb6fab5112fb10ce699b5a80207e5cf571c32/.github/workflows/test.yml#L90C1-L96C18)
6. Compilation not detected by CodeQL.
- The container is not specified in the CodeQL job as shown in the [example workflow](https://docs.github.com/en/code-security/code-scanning/creating-an-advanced-setup-for-code-scanning/running-codeql-code-scanning-in-a-container#example-workflow). It is something worth looking at. It does not make sense however that the CodeQL runner worked on other PRs.

It is worth noting that this is how a successful CodeQL analysis step looks like ([found here]()https://github.com/vapor/vapor/actions/runs/12121164930/job/33791605231?pr=3257):

```
Run github/codeql-action/analyze@v3
While resolving threads, found a cgroup CPUs file with 4 CPUs in /sys/fs/cgroup/cpuset.cpus.effective.
Finalizing swift
Unsetting build tracing environment variables. Subsequent steps of this job will not be traced.
Running queries for swift
Interpreting results for swift
CodeQL scanned 1 out of 282 Swift files in this invocation. Check the status page for overall coverage information: https://github.com/vapor/vapor/security/code-scanning/tools/CodeQL/status/
Analysis produced the following metric data:
```

2024-12-05 07:09 UTC, WilliamFernsV3 commented
> We've found CodeQL to be nothing but flaky when it comes to Swift. I wouldn't spend any time worrying about it.

Thanks.

2024-12-05 07:10 UTC, WilliamFernsV3 commented
@gwynne , feel free to review the PR if and ask for changes if needed. As always, truly love what you and the team here are doing here at Vapor and in server side Swift in general.

2024-12-05 10:20 UTC, WilliamFernsV3 commented
I changed my `Package.swift` to use my fork of Vapor with the changes of this PR as part of `main` branch. 

<img width="804" alt="image" src="https://github.com/user-attachments/assets/b7d11924-cf5f-4082-aa5d-f7fd03972189">

When I use the `custom` validator, when I make a request to the route, I get the following when the custom validation is unsuccessful:

<img width="789" alt="image" src="https://github.com/user-attachments/assets/82b98834-3ce1-44d3-a037-40161047f102">

When it is successful, the route works as expected.

Possible cause: There is something wrong with how errors are handled with the `Custom` validator.

<img width="807" alt="image" src="https://github.com/user-attachments/assets/b7eeb968-b869-4c5a-ac74-fb26ee1e11c1">

Here is the warnings I am getting:

<img width="268" alt="image" src="https://github.com/user-attachments/assets/f52efd65-aa4f-4875-91c0-b6a3305ad7b3">

The first one is from OpenTelemetry, not important.

2024-12-06 06:57 UTC, MrSuddenJoy approved these changes
This code looks good to me. Well done 👍🏻

2024-12-07 03:39 UTC, 0xTim commented
Can we revert all the formatting changes in the test file? It makes it very hard to see what's actually changed.

In terms of the error you're getting, what's in the logs when you send the request?

2024-12-07 06:47 UTC, WilliamFernsV3 commented
> Can we revert all the formatting changes in the test file? It makes it very hard to see what's actually changed.
> 
> In terms of the error you're getting, what's in the logs when you send the request?

Nevermind. This happened because I did not have any middleware configured for my app. I initialized `app.middleware` without providing a custom `ErrorMiddleware`. My fault. 

Will use my own fork now and test the custom validator, and update whether everything worked as expected.

2024-12-07 06:49 UTC, WilliamFernsV3 commented on Tests/VaporTests/ValidationTests.swift
> +                v.add(
@0xTim , this got added

2024-12-07 06:49 UTC, WilliamFernsV3 commented on Tests/VaporTests/ValidationTests.swift
> +                v.add(
@0xTim , this got added.

2024-12-07 06:51 UTC, WilliamFernsV3 commented
> Can we revert all the formatting changes in the test file? It makes it very hard to see what's actually changed.
> 
> In terms of the error you're getting, what's in the logs when you send the request?

Apologise for the formatting. I left comments in as seen above for what I actually changed.

2024-12-07 06:56 UTC, 0xTim commented
The formatting still needs to be reverted to make it possible to review

2024-12-07 06:58 UTC, WilliamFernsV3 commented
> The formatting still needs to be reverted to make it possible to review

Sure. Will do that now.

Here is proof that it works as expected:

Fail:
<img width="841" alt="image" src="https://github.com/user-attachments/assets/ccb7b111-e349-4b4f-8d05-0d49eec00a07">

Success: 
<img width="806" alt="image" src="https://github.com/user-attachments/assets/98566e1e-b0bd-493c-9e99-4a65c0607bdb">

Custom validator:

```swift
       validations.add("userEmail", as: String.self, is: .email)
       validations.add(
           "userEmail",
           as: String.self,
           is: .custom("Validates whether email domain is 'tanner.xyz'.") { email in
               let parts = email.split(separator: "@")
               return parts[parts.count-1] == "tanner.xyz"
           }
       )
```

2024-12-07 07:21 UTC, WilliamFernsV3 commented
> The formatting still needs to be reverted to make it possible to review

Now? Just fixed it.

2024-12-07 23:13 UTC, MrSuddenJoy commented
@WilliamFernsV3 TBH this wasnt needed. Code looked good before; **for me** it does not now.

2024-12-11 04:03 UTC, WilliamFernsV3 commented
> @WilliamFernsV3 TBH this wasnt needed. Code looked good before; **for me** it does not now.

What is wrong with it?

2024-12-11 14:12 UTC, 0xTim requested changes

2024-12-11 14:12 UTC, 0xTim commented on Tests/VaporTests/ValidationTests.swift
> +        custom("123", not: true)
Can we expand these tests a bit, because it's not exactly clear what is happening here. `custom("email")` tests what exactly? I'm assuming that `custom("123", not: true)` tests that "123" != true but what does `custom(true, not: true)` test? We either need some comments or (preferred) expand `custom()` to be clearer about what it's testing

2024-12-12 11:31 UTC, 0xTim commented
> @WilliamFernsV3 nothing wrong programatically wise, just does not look good in IDE. See, Im minimalist, I just like the code to be as short and simple as possible 👍🏻

@MrSuddenJoy These are all additive APIs so you can continue to use the existing APIs

2024-12-12 17:42 UTC, Naveen-C-Ramachandrappa approved these changes

2024-12-15 05:49 UTC, WilliamFernsV3 commented on Tests/VaporTests/ValidationTests.swift
> +        custom("123", not: true)
Better now? Just added comments to explain everything and better naming.

2024-12-17 18:09 UTC, MrSuddenJoy commented on Tests/VaporTests/ValidationTests.swift
> +        validate_value("email")
@0xTim My undersdtanding is that this checks wether email is valid `string` as outlined [in this RFC](https://www.rfc-editor.org/rfc/rfc2822)

2024-12-17 19:05 UTC, 0xTim commented on Tests/VaporTests/ValidationTests.swift
> +        validate_value("email")
No, that's using the `.email` validator. This is for custom validations and just passes in a string

2024-12-20 20:06 UTC, WilliamFernsV3 commented
@0xTim , just simplified the tests to only test the custom validator functionality. Let me know what you think. Thanks :)

2024-12-23 11:02 UTC, 0xTim commented on Tests/VaporTests/ValidationTests.swift
> +    func testCustomValidator() {
@WilliamFernsV3 this doesn't actually test anything right? What's this function here for?

2024-12-30 18:44 UTC, 0xTim approved these changes

2024-12-30 18:52 UTC, merged